RA = ["Road Assets–Toll, Annuity, Hybrid-Annuity", "Road AssetsToll, Annuity, Hybrid-Annuity"]
A = {
"ABRASIVES":["Abrasives & Bearings"],
"ADVERTISING & MARKETING":["Advertising & Media Agencies","Media & Entertainment","Web based media and service","IT Enabled Services","Software Products"],
"AEROSPACE & DEFENCE MANUFACTURING":["Aerospace & Defense","Industrial Products"],
"AGRICULTURE & COMMODITY TRADING":["Trading & Distributors","Other Agricultural Products"],
"AGROCHEMICALS":["Pesticides & Agrochemicals","Specialty Chemicals"],
"AIRLINES":["Airline"],
"AIRPORTS & AVIATION SERVICES":["Airport & Airport services"],
"ALCOHOL & SOLVENT CHEMICALS":["Commodity Chemicals","Breweries & Distilleries"],
"ALCOHOLIC BEVERAGES":["Breweries & Distilleries"],
"ALUMINIUM":["Aluminium","Aluminium, Copper & Zinc Products"],
"APPAREL & FOOTWEAR RETAIL":["Garments & Apparels","Speciality Retail","Footwear","Diversified Retail"],
"APPAREL MANUFACTURING":["Garments & Apparels","Other Textile Products","Trading - Textile Products"],
"AROMA & FLAVOUR CHEMICALS":["Specialty Chemicals","Commodity Chemicals"],
"ASSET MANAGEMENT":["Asset Management Company"],
"AUTO COMPONENTS":["Auto Components & Equipments","Castings & Forgings","Other Industrial Products"],
"AUTO DEALERSHIPS":["Auto -Dealer"],
"AUTO ELECTRICALS & ELECTRONICS":["Auto Components & Equipments","Industrial Products"],
"AUTOMOBILE MANUFACTURERS":["Passenger Cars & Utility Vehicles"],
"BANKING & FINANCIAL SOFTWARE":["Software Products","Computers - Software & Consulting","IT Enabled Services"],
"BATTERIES & ENERGY STORAGE":["Auto Components & Equipments","Household Products","Other Electrical Equipment","Other Industrial Products"],
"BEARINGS":["Abrasives & Bearings","Auto Components & Equipments","Industrial Products","Other Industrial Products"],
"BIOENERGY & DISTILLERY EQUIPMENT":["Industrial Products"],
"BIOFUELS & ETHANOL":["Breweries & Distilleries","Commodity Chemicals","Other Agricultural Products"],
"BIOLOGICS & VACCINES":["Pharmaceuticals","Biotechnology"],
"BOILERS TURBINES & POWER EQUIPMENT":["Heavy Electrical Equipment","Industrial Products","Other Industrial Products"],
"BPM & OUTSOURCING SERVICES":["Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)","IT Enabled Services"],
"BUILDING HARDWARE":["Furniture, Home Furnishing"],
"CARBON BLACK":["Carbon Black"],
"CASTINGS & FOUNDRIES":["Castings & Forgings","Auto Components & Equipments","Other Industrial Products","Industrial Products","Iron & Steel Products"],
"CEMENT":["Cement & Cement Products","Other Construction Materials"],
"CHEMICAL DISTRIBUTION":["Trading - Chemicals","Trading & Distributors"],
"CHLOR-ALKALI & SODA ASH":["Commodity Chemicals"],
"CINEMA EXHIBITION":["Film Production, Distribution & Exhibition"],
"CITY GAS DISTRIBUTION":["LPG/CNG/PNG/LNG Supplier"],
"CLEANROOM & HVAC ENGINEERING":["Industrial Products","Civil Construction"],
"CLOUD COMMUNICATIONS":["Web based media and service","Other Telecom Services","Software Products"],
"COAL & COKE":["Coal","Trading Coal"],
"COLD CHAIN LOGISTICS":["Logistics Solution Provider","Food Storage Facilities"],
"COMMERCIAL VEHICLES":["Commercial Vehicles","Passenger Cars & Utility Vehicles"],
"COMPRESSORS":["Compressors, Pumps & Diesel Engines"],
"CONSTRUCTION & INFRASTRUCTURE EPC":["Civil Construction"],
"CONSTRUCTION & MINING EQUIPMENT":["Industrial Products","Construction Vehicles"],
"CONSUMER APPLIANCES & ELECTRONICS":["Household Appliances","Consumer Electronics","Houseware"],
"CONSUMER CONTRACT MANUFACTURING":["Personal Care","Diversified FMCG","Pharmaceuticals"],
"CONSUMER PRODUCTS":["Diversified Retail","Garments & Apparels","Leisure Products","E-Retail/ E-Commerce","Packaged Foods","Diversified","Gems, Jewellery And Watches","Cigarettes & Tobacco Products"],
"CONTAINER & WAREHOUSE LOGISTICS":["Logistics Solution Provider","Diversified Commercial Services","Food Storage Facilities"],
"COPPER":["Aluminium, Copper & Zinc Products","Copper"],
"COTTON & BLENDED YARN":["Other Textile Products"],
"CREDIT CARDS":["Non Banking Financial Company (NBFC)"],
"CREDIT RATING AGENCIES":["Ratings"],
"CRYOGENIC EQUIPMENT":["Industrial Products","Other Industrial Products"],
"CYBERSECURITY":["Computers - Software & Consulting","Software Products","IT Enabled Services","Consulting Services"],
"DAIRY":["Dairy Products","Other Agricultural Products","Packaged Foods"],
"DATA ANALYTICS & AI SERVICES":["Computers - Software & Consulting"],
"DATA CENTRES & CLOUD INFRASTRUCTURE":["IT Enabled Services"],
"DEFENCE ELECTRONICS":["Aerospace & Defense","Industrial Products"],
"DEFENCE SERVICES":["Aerospace & Defense"],
"DIAGNOSTICS":["Healthcare Service Provider"],
"DIVERSIFIED & OTHER LENDING":["Non Banking Financial Company (NBFC)","Other Financial Services","Investment Company","Financial Institution"],
"DIVERSIFIED BUSINESSES":["Diversified","Holding Company"],
"DIVERSIFIED FINANCIAL SERVICES":["Investment Company","Holding Company","Non Banking Financial Company (NBFC)","Other Financial Services"],
"DIVERSIFIED METALS":["Diversified Metals"],
"DREDGING":["Dredging"],
"DRONES & SPACE TECHNOLOGY":["Aerospace & Defense"],
"DYES & PIGMENTS":["Dyes And Pigments","Specialty Chemicals","Commodity Chemicals"],
"E-COMMERCE & INTERNET RETAIL":["E-Retail/ E-Commerce","Internet & Catalogue Retail"],
"EDIBLE OILS":["Edible Oil","Other Agricultural Products","Other Food Products"],
"EDUCATION & TRAINING":["Education","E-Learning","Software Products"],
"ELECTRIC METERS":["Other Electrical Equipment"],
"ELECTRIC MOBILITY & CHARGING":["Heavy Electrical Equipment","Other Electrical Equipment"],
"ELECTRIC MOTORS & GENERATORS":["Heavy Electrical Equipment","Industrial Products","Other Electrical Equipment"],
"ELECTRICAL EQUIPMENT":["Heavy Electrical Equipment","Other Electrical Equipment","Industrial Products"],
"ELECTRICAL EQUIPMENT REPAIR":["Diversified Commercial Services"],
"ELECTRICAL INSULATORS & BUSHINGS":["Other Electrical Equipment","Other Construction Materials"],
"ELECTRONIC COMPONENTS & MATERIALS":["Other Electrical Equipment","Industrial Products","Other Industrial Products"],
"ELECTRONIC EQUIPMENT":["Industrial Products","Other Industrial Products"],
"ELECTRONICS MANUFACTURING SERVICES":["Industrial Products","Consumer Electronics","Household Appliances","Aerospace & Defense","Other Electrical Equipment","Telecom -  Equipment & Accessories"],
"ELECTRONICS RETAIL":["Speciality Retail","Diversified Retail"],
"ENGINEERING CONSULTANCY":["Civil Construction"],
"ENGINEERING R&D SERVICES":["IT Enabled Services","Computers - Software & Consulting"],
"EVENTS & EXHIBITIONS":["Other Consumer Services","Diversified Commercial Services"],
"EXCHANGE-TRADED FUNDS":[None],
"EXPLOSIVES":["Explosives","Specialty Chemicals"],
"EXPRESS & PARCEL LOGISTICS":["Logistics Solution Provider"],
"EYEWEAR":["Speciality Retail"],
"FABRICS & TEXTILE PROCESSING":["Other Textile Products","Garments & Apparels","Trading - Textile Products"],
"FASTENERS":["Auto Components & Equipments","Industrial Products"],
"FERRO ALLOYS":["Ferro & Silica Manganese","Iron & Steel Products","Iron & Steel"],
"FERTILIZERS":["Fertilizers","Commodity Chemicals"],
"FILM MUSIC & CONTENT":["Film Production, Distribution & Exhibition","Media & Entertainment","TV Broadcasting & Software Production","Digital Entertainment"],
"FINANCIAL DATA & RESEARCH":[],
"FINANCIAL PRODUCT DISTRIBUTION":["Financial Products Distributor"],
"FLEXIBLE HOSES & PIPING SYSTEMS":["Iron & Steel Products","Industrial Products"],
"FLEXIBLE PACKAGING & FILMS":["Packaging","Plastic Products - Industrial","Plastic Products - Consumer"],
"FLEXIBLE WORKSPACES":["Diversified Commercial Services"],
"FLUOROCHEMICALS":["Specialty Chemicals","Commodity Chemicals"],
"FOOD & AGRICULTURAL MACHINERY":["Industrial Products","Other Industrial Products"],
"FOOD DELIVERY & QUICK COMMERCE":["E-Retail/ E-Commerce"],
"FOOTWEAR":["Footwear","Leather And Leather Products"],
"FOREIGN EXCHANGE & REMITTANCES":["Other Financial Services","Financial Technology (Fintech)"],
"FORGINGS":["Auto Components & Equipments","Castings & Forgings","Iron & Steel Products"],
"FOUNDRY & METAL PROCESSING EQUIPMENT":["Industrial Products"],
"FREIGHT FORWARDING & LOGISTICS":["Logistics Solution Provider","Road Transport","Transport Related Services"],
"FURNITURE & HOME PRODUCTS":["Furniture, Home Furnishing","Plastic Products - Consumer","Houseware"],
"GAS CYLINDERS & CONTAINERS":["Industrial Products","Other Industrial Products"],
"GAS TRANSMISSION & LNG":["LPG/CNG/PNG/LNG Supplier","Gas Transmission/Marketing"],
"GELATIN & FOOD INGREDIENTS":["Specialty Chemicals"],
"GENERAL INSURANCE":["General Insurance"],
"GEOSPATIAL & MAPPING":["IT Enabled Services","Software Products"],
"GLASS":["Glass - Industrial","Glass - Consumer","Packaging","Auto Components & Equipments","Other Construction Materials"],
"GOLD FINANCE":["Non Banking Financial Company (NBFC)"],
"GRAPHITE & CARBON MATERIALS":["Carbon Black","Petrochemicals"],
"GRAPHITE ELECTRODES":["Electrodes & Refractories"],
"HEALTH INSURANCE":["General Insurance"],
"HEALTHCARE ADMINISTRATION SERVICES":["Insurance Distributors"],
"HEAT EXCHANGERS & PROCESS EQUIPMENT":["Industrial Products","Other Industrial Products"],
"HOME TEXTILES":["Other Textile Products","Furniture, Home Furnishing"],
"HOSPITALS":["Hospital","Healthcare Service Provider"],
"HOTELS & RESORTS":["Hotels & Resorts"],
"HOUSING FINANCE":["Housing Finance Company"],
"HYDRAULICS & MOTION CONTROL":["Industrial Products","Other Industrial Products","Auto Components & Equipments","Compressors, Pumps & Diesel Engines"],
"INDUSTRIAL AUTOMATION & INSTRUMENTATION":["Industrial Products","Other Electrical Equipment"],
"INDUSTRIAL ENGINES":["Compressors, Pumps & Diesel Engines"],
"INDUSTRIAL FILTERS & SEPARATION":["Industrial Products"],
"INDUSTRIAL FURNACES & HEATING":["Industrial Products"],
"INDUSTRIAL GASES":["Industrial Gases","Commodity Chemicals"],
"INDUSTRIAL GEARS & TRANSMISSION":["Industrial Products","Other Industrial Products","Heavy Electrical Equipment"],
"INDUSTRIAL HVAC & REFRIGERATION":["Industrial Products"],
"INDUSTRIAL MACHINERY":["Industrial Products","Other Industrial Products"],
"INDUSTRIAL MINERALS & MINING":["Industrial Minerals","Granites & Marbles","Trading - Minerals"],
"INDUSTRIAL PLASTICS & COMPOSITES":["Plastic Products - Industrial","Plastic Products - Consumer"],
"INDUSTRIAL RUBBER PRODUCTS":["Rubber","Tyres & Rubber Products"],
"INDUSTRIAL SAFETY PRODUCTS":["Other Industrial Products"],
"INDUSTRIAL TOOLS":["Iron & Steel Products"],
"INFRASTRUCTURE FINANCE":["Financial Institution","Non Banking Financial Company (NBFC)"],
"INFRASTRUCTURE INVESTMENT TRUSTS":RA+[None,"Power - Transmission","Civil Construction","Diversified Commercial Services"],
"INORGANIC & COMMODITY CHEMICALS":["Specialty Chemicals","Commodity Chemicals"],
"INSURANCE DISTRIBUTION":["Financial Technology (Fintech)","Insurance Distributors"],
"INTEGRATED TEXTILES":["Other Textile Products","Garments & Apparels","Trading - Textile Products"],
"INTERNET PLATFORMS":["Internet & Catalogue Retail","IT Enabled Services","E-Retail/ E-Commerce","Computers - Software & Consulting"],
"INVESTMENT HOLDING COMPANIES":["Investment Company","Non Banking Financial Company (NBFC)","Holding Company","Other Financial Services","Other Capital Market related Services"],
"IRON ORE & MANGANESE MINING":["Industrial Minerals"],
"IT HARDWARE & DISTRIBUTION":["Computers Hardware & Equipments","Trading & Distributors"],
"IT SERVICES & CONSULTING":["Computers - Software & Consulting","IT Enabled Services","Software Products","Consulting Services","Data Processing Services"],
"JEWELLERY RETAIL & MANUFACTURING":["Gems, Jewellery And Watches","Speciality Retail"],
"JUTE PRODUCTS":["Jute & Jute Products","Other Textile Products"],
"LEATHER & LEATHER PRODUCTS":["Leather And Leather Products"],
"LEISURE & GAMING":["Amusement Parks/ Other Recreation","Digital Entertainment"],
"LIFE INSURANCE":["Life Insurance"],
"LIGHTING & ELECTRICAL ACCESSORIES":["Other Electrical Equipment","Consumer Electronics","Household Appliances"],
"LUBRICANTS & SPECIALTY OILS":["Lubricants"],
"LUGGAGE & TRAVEL ACCESSORIES":["Plastic Products - Consumer","Diversified consumer products"],
"MACHINE TOOLS":["Industrial Products"],
"MATERIAL HANDLING EQUIPMENT":["Industrial Products"],
"MEAT & POULTRY PROCESSING":["Meat Products including Poultry"],
"MEDICAL DEVICES & SUPPLIES":["Medical Equipment & Supplies"],
"METAL FABRICATION & ENGINEERING":["Industrial Products","Other Industrial Products","Auto Components & Equipments","Castings & Forgings"],
"METAL PACKAGING":["Packaging"],
"METAL RECYCLING":["Aluminium, Copper & Zinc Products","Diversified Metals","Trading - Metals"],
"METAL TRADING":["Trading & Distributors","Trading - Metals"],
"MICROFINANCE":["Microfinance Institutions","Non Banking Financial Company (NBFC)"],
"MOTORCYCLE HELMETS & SAFETY ACCESSORIES":["Auto Components & Equipments"],
"NON-ALCOHOLIC BEVERAGES":["Other Beverages"],
"NON-FERROUS METALS":[],
"NUTRACEUTICALS & CONSUMER HEALTH":["Pharmaceuticals","Packaged Foods","Other Food Products","Biotechnology","Wellness"],
"OIL & GAS EPC":["Civil Construction"],
"OIL & GAS EXPLORATION":["Oil Exploration & Production"],
"OIL REFINING & MARKETING":["Refineries & Marketing"],
"OILFIELD & DRILLING SERVICES":["Offshore Support Solution Drilling","Oil Equipment & Services","Shipping"],
"PACKAGED FOODS & FOOD PROCESSING":["Packaged Foods","Other Agricultural Products","Other Food Products"],
"PACKAGING PRODUCTS":["Packaging","Plastic Products - Industrial","Paper & Paper Products"],
"PAINTS COATINGS & ADHESIVES":["Paints","Specialty Chemicals","Dyes And Pigments","Commodity Chemicals"],
"PAPER & PAPERBOARD":["Paper & Paper Products","Packaging"],
"PASSENGER VEHICLES":["Passenger Cars & Utility Vehicles"],
"PAYMENTS & FINTECH":["Financial Technology (Fintech)","Other Financial Services","Computers - Software & Consulting","IT Enabled Services","Software Products","Other Bank"],
"PERSONAL & HOME SERVICES":["E-Retail/ E-Commerce"],
"PERSONAL CARE & HOUSEHOLD PRODUCTS":["Personal Care","Household Products","Diversified FMCG"],
"PETROCHEMICALS & POLYMERS":["Commodity Chemicals","Petrochemicals","Trading - Chemicals","Specialty Chemicals"],
"PETROLEUM PRODUCTS & TRADING":["Petrochemicals","Refineries & Marketing","Lubricants","Trading & Distributors"],
"PHARMA APIS & INTERMEDIATES":["Pharmaceuticals"],
"PHARMA CONTRACT RESEARCH & MANUFACTURING":["Pharmaceuticals","Healthcare Research, Analytics & Technology","Biotechnology"],
"PHARMA DISTRIBUTION & RETAIL":["Pharmacy Retail","Trading & Distributors"],
"PHARMA EXCIPIENTS":["Pharmaceuticals","Specialty Chemicals"],
"PHARMA FORMULATIONS":["Pharmaceuticals"],
"PLASTIC & PACKAGING MACHINERY":["Industrial Products"],
"PLASTIC PIPES & FITTINGS":["Plastic Products - Industrial"],
"PLYWOOD LAMINATES & BOARDS":["Plywood Boards/ Laminates","Furniture, Home Furnishing","Forest Products"],
"POLLUTION CONTROL EQUIPMENT":["Industrial Products"],
"PORTS & TERMINALS":["Port & Port services"],
"POULTRY & ANIMAL FEED":["Animal Feed","Other Agricultural Products","Meat Products including Poultry"],
"POWER ELECTRONICS":["Heavy Electrical Equipment","Industrial Products","Other Electrical Equipment"],
"POWER GENERATION & INTEGRATED UTILITIES":["Power Generation","Integrated Power Utilities"],
"POWER T&D EPC":["Civil Construction","Heavy Electrical Equipment"],
"POWER TRADING":["Exchange and Data Platform","Power Trading"],
"POWER TRANSMISSION & DISTRIBUTION UTILITIES":["Integrated Power Utilities","Power Distribution","Power - Transmission"],
"PRECIOUS METALS":["Precious Metals"],
"PRINTING SERVICES":["Printing & Publication"],
"PRIVATE SECTOR BANKS":["Private Sector Bank"],
"PROFESSIONAL & BUSINESS SERVICES":["Consulting Services","Diversified Commercial Services"],
"PUBLIC SECTOR BANKS":["Public Sector Bank"],
"PUBLISHING & NEWS":["Print Media","Electronic Media","Printing & Publication"],
"PUMPS":["Compressors, Pumps & Diesel Engines","Industrial Products","Heavy Electrical Equipment"],
"RAIL LOGISTICS":["Logistics Solution Provider"],
"RAILWAY CATERING & TOURISM":["Tour, Travel Related Services"],
"RAILWAY EPC":["Civil Construction"],
"RAILWAY EQUIPMENT":["Railway Wagons","Industrial Products","Construction Vehicles","Iron & Steel Products"],
"REAL ESTATE DEVELOPMENT":["Residential, Commercial Projects","Real Estate related services"],
"REAL ESTATE SERVICES":["Real Estate related services","Diversified Commercial Services"],
"REFRACTORIES":["Electrodes & Refractories"],
"REGISTRARS & FUND SERVICES":["Depositories, Clearing Houses and Other Intermediaries"],
"REITS":[None,"Real Estate Investment Trusts (REITs)"],
"RENEWABLE ENERGY EPC":["Other Electrical Equipment","Civil Construction"],
"RENEWABLE ENERGY SOLUTIONS":["Power Generation","Other Electrical Equipment","Civil Construction","Industrial Products"],
"RENEWABLE O&M SERVICES":["Diversified Commercial Services"],
"RENEWABLE POWER GENERATION":["Power Generation"],
"RESTAURANTS & QSR":["Restaurants"],
"RETAIL CHAINS":["Diversified Retail","Speciality Retail"],
"RICE & GRAIN PROCESSING":["Other Agricultural Products","Packaged Foods","Other Food Products"],
"RIGID PLASTIC PACKAGING":["Packaging","Plastic Products - Consumer","Plastic Products - Industrial"],
"ROAD ASSET OPERATORS":RA,
"ROAD CONSTRUCTION":["Civil Construction"]+RA,
"RUBBER CHEMICALS":["Specialty Chemicals","Commodity Chemicals"],
"SALT":["Other Food Products"],
"SEAFOOD & AQUACULTURE":["Seafood","Other Food Products","Packaged Foods"],
"SECURITY & SURVEILLANCE EQUIPMENT":["Industrial Products","Aerospace & Defense"],
"SEEDS & AGRICULTURAL INPUTS":["Other Agricultural Products"],
"SEMICONDUCTORS & ELECTRONIC COMPONENTS":["Industrial Products","Other Electrical Equipment","Computers Hardware & Equipments"],
"SHIPBUILDING & SHIP REPAIR":["Ship Building & Allied Services","Aerospace & Defense"],
"SHIPPING OPERATORS":["Shipping"],
"SMALL FINANCE BANKS":["Other Bank"],
"SOFTWARE PRODUCTS & PLATFORMS":["Computers - Software & Consulting","Software Products","IT Enabled Services","Data Processing Services"],
"SOLAR CELLS & MODULES":["Other Electrical Equipment","Heavy Electrical Equipment"],
"SPECIALTY ALLOYS":["Aerospace & Defense"],
"SPECIALTY CHEMICALS":["Specialty Chemicals","Commodity Chemicals","Dyes And Pigments","Petrochemicals"],
"STAFFING & FACILITY MANAGEMENT":["Diversified Commercial Services","Consulting Services","Other Consumer Services"],
"STAINLESS STEEL":["Iron & Steel Products","Iron & Steel"],
"STATIONERY & EDUCATION PRODUCTS":["Stationary","Printing & Publication"],
"STEEL & IRON":["Iron & Steel Products","Iron & Steel","Sponge Iron","Pig Iron"],
"STEEL PIPES & TUBES":["Iron & Steel Products","Iron & Steel"],
"STEEL WIRE & WIRE ROPES":["Iron & Steel Products"],
"STOCK EXCHANGES & DEPOSITORIES":["Exchange and Data Platform","Depositories, Clearing Houses and Other Intermediaries"],
"STOCKBROKING & INVESTMENT BANKING":["Stockbroking & Allied","Other Capital Market related Services","Other Financial Services"],
"STONE & OTHER BUILDING MATERIALS":["Other Construction Materials","Granites & Marbles","Cement & Cement Products"],
"SUGAR & INTEGRATED ETHANOL":["Sugar"],
"SWITCHGEAR & GRID EQUIPMENT":["Other Electrical Equipment","Heavy Electrical Equipment","Industrial Products"],
"SYNTHETIC FIBRES & YARNS":["Other Textile Products","Petrochemicals","Trading - Textile Products"],
"SYNTHETIC RUBBER & LATEX":["Rubber"],
"TEA & COFFEE":["Tea & Coffee","Other Agricultural Products"],
"TECHNICAL TEXTILES":["Other Textile Products","Trading - Textile Products","Packaging"],
"TELECOM EQUIPMENT & OPTICAL FIBRE":["Telecom -  Equipment & Accessories","Telecom - Infrastructure"],
"TELECOM OPERATORS":["Telecom - Cellular & Fixed line services"],
"TELECOM TOWERS & INFRASTRUCTURE":["Telecom - Infrastructure","Other Telecom Services"],
"TESTING INSPECTION & CERTIFICATION":["Diversified Commercial Services"],
"TEXTILE MACHINERY":["Industrial Products"],
"TILES & SANITARYWARE":["Ceramics","Sanitary Ware"],
"TOBACCO":["Cigarettes & Tobacco Products","Diversified FMCG"],
"TOYS & LEISURE PRODUCTS":["Leisure Products"],
"TRACTORS":["Tractors","Construction Vehicles"],
"TRADING & DISTRIBUTION":["Trading & Distributors","Distributors","Trading - Textile Products","Trading - Metals","Trading - Chemicals","Trading - Minerals"],
"TRANSFORMER COMPONENTS":["Other Electrical Equipment"],
"TRANSFORMERS":["Heavy Electrical Equipment","Other Electrical Equipment"],
"TRANSMISSION TOWERS & STRUCTURES":["Heavy Electrical Equipment"],
"TRAVEL & TOURISM":["Tour, Travel Related Services"],
"TRUSTEESHIP & CORPORATE ADVISORY":["Other Financial Services"],
"TV & RADIO BROADCASTING":["TV Broadcasting & Software Production","Media & Entertainment"],
"TWO & THREE WHEELERS":["2/3 Wheelers","Commercial Vehicles"],
"TYRES":["Tyres & Rubber Products"],
"VALVES":["Industrial Products","Other Industrial Products"],
"VEHICLE FINANCE":["Non Banking Financial Company (NBFC)"],
"VEHICLE RENTAL & MOBILITY SERVICES":["Road Transport"],
"WASTE MANAGEMENT & RECYCLING":["Waste Management"],
"WATCHES & ACCESSORIES":["Gems, Jewellery And Watches"],
"WATER INFRASTRUCTURE & TREATMENT":["Water Supply & Management","Waste Management","Civil Construction"],
"WEALTH MANAGEMENT":["Stockbroking & Allied","Other Financial Services","Financial Products Distributor"],
"WELDING & CUTTING EQUIPMENT":["Other Industrial Products","Other Electrical Equipment","Industrial Products"],
"WIND TURBINES & EQUIPMENT":["Heavy Electrical Equipment"],
"WIRES CABLES & CONDUCTORS":["Cables - Electricals","Other Electrical Equipment","Aluminium, Copper & Zinc Products","Telecom -  Equipment & Accessories"],
"ZINC & LEAD":["Zinc","Diversified Metals"],
}
