# verdict: W = wrong (move), K = keep, R = needs human review ; conf H/M
D = {
"NSE:ASPIRE":("W","CONSUMER APPLIANCES & ELECTRONICS","H","Makes and sells electronic equipment and home appliances; no advertising business"),
"NSE:BLUEPEBBLE":("K",None,"M","In-store/office branding design and installation"),
"NSE:GYFTR":("R",None,"M","Renamed entity; official record still describes an NBFC/share-trading business - confirm current business"),
"NSE:HEADSUP":("W","APPAREL & FOOTWEAR RETAIL","M","Trades garments"),
"NSE:NAMAN":("W","FURNITURE & HOME PRODUCTS","H","Retail and industrial fixtures"),
"BSE:RADIXIND":("W","PERSONAL CARE & HOUSEHOLD PRODUCTS","H","Human hair products"),
"BSE:SPTRSHI":("W","PACKAGED FOODS & FOOD PROCESSING","H","Mushrooms and agro products"),
"NSE:ABANSENT":("K",None,"M","Trades agri commodities, precious metals"),
"BSE:ADISHAKTI":("W","METAL TRADING","H","Trades tin plates, ETP sheets"),
"BSE:AMRAAGRI":("K",None,"M","Trades agri products"),
"BSE:ANIRIT":("K",None,"M","Agri, agri-biogas, agri-waste"),
"BSE:ARMAN":("W","TRADING & DISTRIBUTION","M","Deals in textiles, precious metals & stones, plastics - general trader, not agri"),
"BSE:ASHAI":("K",None,"M","Trading and financing"),
"BSE:DELTA":("W","TRADING & DISTRIBUTION","M","Historically traded diamonds/precious stones and metals; no agri activity"),
"NSE:FRESHARA":("W","PACKAGED FOODS & FOOD PROCESSING","H","Producer/exporter of preserved gherkins"),
"BSE:GALAGEX":("W","FORGINGS","H","Manufactures forged rings"),
"BSE:GAYATRIBI":("W","PACKAGED FOODS & FOOD PROCESSING","M","Starch and starch-derivative manufacturer (agro-processing), not a trader"),
"BSE:GUJTLRM":("K",None,"M","Diversified trading incl. agri commodities"),
"BSE:MPAGI":("R","FERTILIZERS","M","Fertilizer licence, no manufacturing, no operating revenue FY26 - dormant"),
"BSE:MERCTRD":("K",None,"H","Trades agri products"),
"BSE:MIDINDIA":("W","REAL ESTATE DEVELOPMENT","M","Real estate and trading"),
"BSE:MRUTR":("K",None,"M","Commodity trading, commission income"),
"BSE:PVVINFRA":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Construction and renewable energy"),
"BSE:PAJSON":("W","PACKAGED FOODS & FOOD PROCESSING","H","Cashew processing"),
"BSE:RGRL":("R",None,"M","Official description vague ('services industries and allied activities')"),
"NSE:SHANTI":("K",None,"H","Agri commodity processing and trading"),
"NSE:SHIVAAGRO":("W","FERTILIZERS","H","Manufactures and trades fertilizers"),
"BSE:SHIVAGR":("W","FOOD & AGRICULTURAL MACHINERY","M","Rolling and forging of agricultural implements"),
"NSE:VASUPRADA":("W","TEA & COFFEE","H","Tea, coffee and rubber plantations"),
"BSE:SURATRAML":("K",None,"M","Commodity trading"),
"BSE:VPL":("K",None,"M","Nursery plants, landscaping"),
"BSE:ZODIACVEN":("W","REAL ESTATE DEVELOPMENT","H","Real estate development"),
"BSE:ACCEL":("W","IT SERVICES & CONSULTING","H","IT services (plus animation, IT real estate)"),
"NSE:AUSOMENT":("W","JEWELLERY RETAIL & MANUFACTURING","H","Jewellery manufacturing/trading and commodity/financial market trading"),
"NSE:CONTI":("W","AGRICULTURE & COMMODITY TRADING","M","Deals in wheat, paddy, cereals, mentha oil and seeds"),
"NSE:DHANLAXMI":("W","SEEDS & AGRICULTURAL INPUTS","H","Manufacturing/processing of agricultural seeds"),
"NSE:KHAICHEM":("W","FERTILIZERS","H","Single Super Phosphate fertiliser, sulphuric acid"),
"NSE:KHAITANLTD":("W","CONSUMER APPLIANCES & ELECTRONICS","M","Trades electrical goods (fans, lights, pumps); small agri/sugar presence"),
"NSE:MBAPL":("W","FERTILIZERS","H","SSP/DAP/NPK fertiliser and sulphuric acid"),
"NSE:NITIRAJ":("W","ELECTRONIC EQUIPMENT","H","Electronic weighing scales, currency counters, fare meters"),
"BSE:PARKERAC":("W","CONTAINER & WAREHOUSE LOGISTICS","H","Rents out its storage tank farm; no agrochem business"),
"NSE:OSWALSEEDS":("W","SEEDS & AGRICULTURAL INPUTS","H","Grain seed selling"),
"NSE:GLOBALVECT":("K",None,"M","Helicopter charter services"),
"BSE:RDBIPL":("W","REAL ESTATE DEVELOPMENT","H","Real estate construction and development"),
"NSE:TARMAT":("W","ROAD CONSTRUCTION","H","Builds airfields and highways (contractor, not an airport operator)"),
"NSE:VIJSOLX":("W","EDIBLE OILS","H","Edible oil and vanaspati ('Solvex' = solvent extraction of oilseeds)"),
"BSE:CHMBBRW":("K",None,"M","IMFL and beer trading/retail"),
"NSE:GRANDOAK":("R","ALCOHOLIC BEVERAGES","M","Renamed from Pacheli Industrial Finance; official record still shows financing - confirm distillery business has started"),
"BSE:KFBL":("W","GELATIN & FOOD INGREDIENTS","H","Makes yeast only"),
"BSE:NSL":("K",None,"H","Imports and distributes liquor"),
"NSE:PHOENXINTL":("R",None,"M","Building leasing plus shoe uppers; not alcoholic beverages"),
"NSE:ALUFLUOR":("W","INORGANIC & COMMODITY CHEMICALS","M","Aluminium fluoride (a chemical sold to smelters), not an aluminium producer"),
"NSE:GOYALALUM":("K",None,"H","Aluminium coils/sheets"),
"BSE:INNOVATORS":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Facade systems design, fabrication, installation"),
"BSE:NIRAVCOM":("K",None,"M","Aluminium doors and windows"),
"BSE:WWALUM":("W","METAL TRADING","M","Trades aluminium coils"),
"BSE:KAMADGIRI":("W","FABRICS & TEXTILE PROCESSING","M","Fabric and apparel manufacturer, not a retailer"),
"NSE:RAYMONDLSL":("K",None,"M","Branded apparel with retail network"),
"BSE:SCARNOSE":("W","POULTRY & ANIMAL FEED","M","Animal food products"),
"NSE:BIL":("K",None,"M","Leather and textile products"),
"BSE:LWSKNIT":("K",None,"H","Garments"),
"NSE:MINALIND":("W","JEWELLERY RETAIL & MANUFACTURING","H","Diamantaire and jewellery"),
"NSE:CBAZAAR":("W","E-COMMERCE & INTERNET RETAIL","H","Sells designer clothes online (Cbazaar)"),
"BSE:NEWLIGHT":("K",None,"M","Textile/uniform trading"),
"BSE:SHOORA":("W","JEWELLERY RETAIL & MANUFACTURING","H","Diamonds and jewellery"),
"BSE:SIDDHEGA":("R",None,"M","Trading and investing liquid funds - no garment activity described"),
"BSE:SKL":("K",None,"H","Knitted fabric and garments"),
"BSE:YORKEXP":("K",None,"H","Hosiery garments"),
"NSE:ZENITHEXPO":("K",None,"M","Leather goods and fabrics"),
"NSE:AMBICAAGAR":("W","PERSONAL CARE & HOUSEHOLD PRODUCTS","H","Incense sticks (agarbatti)"),
"BSE:MRCAGRO":("W","EDIBLE OILS","H","Edible oils and food products"),
"BSE:DYNAMICP":("W","DIVERSIFIED & OTHER LENDING","H","Loans and financing, not asset management"),
"NSE:JMA":("K",None,"M","Auto spare parts distribution"),
"NSE:TECHLABS":("R",None,"M","Official record: goods sales plus power-sector consultancy - confirm battery business"),
"NSE:QLINE":("W","MEDICAL DEVICES & SUPPLIES","M","Diagnostic reagents"),
"NSE:HIGREEN":("W","WASTE MANAGEMENT & RECYCLING","M","Recycles waste rubber/tyres into fuel oil (pyrolysis)"),
"NSE:PCCL":("W","GRAPHITE & CARBON MATERIALS","M","Calcined petroleum coke"),
"NSE:AUROIMPEX":("W","POLLUTION CONTROL EQUIPMENT","H","Electrostatic precipitator electrodes and parts"),
"NSE:KCK":("K",None,"M","Chemicals/dyes trading"),
"NSE:AISL":("W","STAFFING & FACILITY MANAGEMENT","H","Manpower deputation"),
"NSE:MAHESHWARI":("K",None,"M","Transport plus paper and coal trading"),
"NSE:GPECO":("W","RENEWABLE ENERGY EPC","H","Solar plants/panels"),
"NSE:GGBL":("W","RENEWABLE ENERGY EPC","M","Solar modules, solar systems, electrical contracting"),
"NSE:INDIFRA":("K",None,"M","Infra/construction services"),
"NSE:MASON":("K",None,"H","Infra construction"),
"NSE:SARTELE":("W","TELECOM TOWERS & INFRASTRUCTURE","M","Builds 4G/5G telecom towers"),
"NSE:SHRADHA":("K",None,"M","Building and engineering services"),
"NSE:TEAMTECH":("K",None,"M","Formwork systems for construction"),
"NSE:VIESL":("W","CONSTRUCTION & MINING EQUIPMENT","M","Rents/sells road construction equipment"),
"NSE:GKWLIMITED":("K",None,"M","Warehousing plus treasury"),
"NSE:KLL":("K",None,"M","C&F agency and transport"),
"NSE:AVIENCE":("W","MEDICAL DEVICES & SUPPLIES","H","Manufactures molecular diagnostic kits (product maker, not a lab chain)"),
"NSE:QMSMEDI":("W","MEDICAL DEVICES & SUPPLIES","H","Medical device manufacturer/distributor"),
"NSE:QUESTLAB":("W","PHARMA FORMULATIONS","H","Pharmaceutical manufacturer"),
"NSE:SAAKSHI":("W","ELECTRICAL EQUIPMENT","M","Electrical control panels, X-ray systems, wire harness"),
"NSE:TEMBO":("W","METAL FABRICATION & ENGINEERING","H","Fabricated metal products"),
"NSE:ZTECH":("K",None,"M","Theme parks, wastewater, geotech"),
"NSE:DRONE":("K",None,"H","Drone manufacturing and pilot training"),
"NSE:SIKKO":("W","AGROCHEMICALS","H","Pesticide/fertiliser/seed formulator, no dyes or pigments"),
"NSE:ROCKINGDCE":("K",None,"M","Refurbished electronics / liquidation trading"),
"NSE:CHETANA":("K",None,"M","K-12 textbook publisher"),
"NSE:WINNY":("K",None,"M","Immigration/visa coaching"),
"NSE:SHREEOSFM":("W","VEHICLE RENTAL & MOBILITY SERVICES","H","Vehicle rentals / employee transport"),
"NSE:LATTEYS":("W","PUMPS","H","Solar pumps"),
"NSE:RULKA":("K",None,"M","Electrical and fire-fighting contracting"),
"NSE:PANACHE":("K",None,"H","Electronics design and manufacturing"),
"NSE:GRADIENTE":("K",None,"M","Advertising and TV serial production"),
"NSE:SONAMLTD":("W","WATCHES & ACCESSORIES","H","Clocks and clock movements"),
"NSE:SELLOWRAP":("W","AUTO COMPONENTS","M","Custom components for automotive and white goods"),
"NSE:PURPLEUTED":("W","APPAREL & FOOTWEAR RETAIL","M","Fashion brand: clothing, shoes, accessories"),
"NSE:BMETRICS":("W","TRADING & DISTRIBUTION","M","Engineering tools and metals trading, not logistics"),
"NSE:CREDENT":("R",None,"M","Healthcare services plus logistics - mixed"),
"NSE:TARACHAND":("K",None,"M","Cargo handling and logistics"),
"NSE:ELGNZ":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Turnkey interior fit-outs"),
"NSE:WINSOL":("W","RENEWABLE O&M SERVICES","H","Wind/solar O&M and commissioning"),
"NSE:MADHAVBAUG":("K",None,"H","Clinics/hospitals"),
"NSE:CANARYS":("W","IT SERVICES & CONSULTING","M","Software/hardware development and consultancy"),
"NSE:RBMINFRA":("W","OIL & GAS EPC","M","Engineering, execution and O&M of rotary equipment for refineries and plants"),
"NSE:SONUINFRA":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Mechanical and civil construction"),
"NSE:SUMAX":("W","AUTO COMPONENTS","H","Products for auto OEM and refinish markets"),
"NSE:MGSL":("W","GEOSPATIAL & MAPPING","H","Geospatial technology and engineering consultancy"),
"NSE:VISHNUINFR":("K",None,"M","Quarrying/M-sand plus infra projects"),
"NSE:KSHITIJPOL":("K",None,"M","Plastic sheets and films"),
"NSE:ANLON":("R",None,"M","Engineering services/training/consultancy - confirm safety-products revenue"),
"NSE:MCON":("W","SPECIALTY CHEMICALS","M","Construction chemicals and building materials"),
"NSE:YCCL":("K",None,"M","Chemicals trading, dyes and intermediates"),
"NSE:SHRITECH":("W","TECHNICAL TEXTILES","H","Non-woven technical textiles"),
"NSE:SKYTECH":("W","INDUSTRIAL AUTOMATION & INSTRUMENTATION","H","Control and automation"),
"NSE:KALYANI":("W","AUTO DEALERSHIPS","H","Heavy commercial vehicle dealership plus fuel station"),
"NSE:ROXHITECH":("W","IT SERVICES & CONSULTING","M","IT services, system integration, managed services"),
"NSE:ACEINTEG":("W","STAFFING & FACILITY MANAGEMENT","H","Manpower recruitment contracts"),
"NSE:ESCONET":("K",None,"M","IT infrastructure system integrator"),
"NSE:REPL":("W","ENGINEERING CONSULTANCY","H","Real estate and infrastructure consultants"),
"NSE:TRIDHYA":("K",None,"H","IT solutions"),
"NSE:SIGNORIA":("W","APPAREL MANUFACTURING","H","Women's apparel manufacturer"),
"NSE:ABMINTLLTD":("W","TRADING & DISTRIBUTION","M","Imports plastic raw materials; no leather business"),
"NSE:SCML":("K",None,"M","Lathe chucks and machine-tool accessories"),
"NSE:YASHOPTICS":("K",None,"M","Ophthalmic lenses"),
"NSE:AHLADA":("K",None,"M","Steel doors/windows"),
"NSE:EFORCE":("W","ELECTRICAL EQUIPMENT","M","Electrical component products"),
"NSE:AATMAJ":("W","HOSPITALS","H","Multi-speciality hospital"),
"NSE:CHANDAN":("W","DIAGNOSTICS","H","Diagnostic centres"),
"NSE:PRAMODINI":("W","DIAGNOSTICS","H","Diagnostic services"),
"NSE:APOLSINHOT":("W","RESTAURANTS & QSR","M","Food outlets and catering at hospitals/institutions"),
"NSE:MVKAGRO":("W","SUGAR & INTEGRATED ETHANOL","H","Integrated sugar manufacturer"),
"NSE:KRISHCA":("K",None,"M","Steel strapping / packaging solutions"),
"NSE:SRIVASAVI":("K",None,"H","Adhesive tapes"),
"NSE:MHHL":("K",None,"M","Hygiene products"),
"NSE:ONDOOR":("W","RETAIL CHAINS","M","Grocery/household retail via stores and e-commerce"),
"NSE:GLOBALPET":("W","PLASTIC & PACKAGING MACHINERY","H","Makes PET bottle machines, not polymers"),
"NSE:BALAXI":("K",None,"M","Branded/generic medicines supply"),
"NSE:MAITREYA":("W","HOSPITALS","H","Multi-speciality hospital"),
"NSE:ARVEE":("W","SPECIALTY CHEMICALS","H","Specialty chemicals manufacturer"),
"NSE:SAROJA":("W","CHEMICAL DISTRIBUTION","H","Trades thionyl chloride and pharma intermediates"),
"NSE:JAYBEE":("W","TRANSFORMER COMPONENTS","H","CRGO silicon steel cores for transformers"),
"NSE:FALCONTECH":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","MEP contracting, not ports"),
"NSE:VIVO":("W","CLOUD COMMUNICATIONS","H","Cloud telephony"),
"NSE:CGRAPHICS":("K",None,"M","Printing plates and inks"),
"NSE:GRAPHISAD":("W","ADVERTISING & MARKETING","H","Advertising and communications agency"),
"NSE:ALLETEC":("W","IT SERVICES & CONSULTING","H","Technology/ERP solutions"),
"NSE:CMRSL":("K",None,"H","Market research and consultancy"),
"NSE:ENFUSE":("W","BPM & OUTSOURCING SERVICES","M","Digital/data services"),
"NSE:SADHAV":("W","SHIPPING OPERATORS","H","Owns/operates barges, tugs, vessels"),
"NSE:E2ERAIL":("W","RAILWAY EPC","H","Railway system integration and engineering"),
"NSE:CHAVDA":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Construction contractor"),
"NSE:INTEGRITY":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Class-A civil contractor"),
"NSE:LLOYDS":("W","PERSONAL & HOME SERVICES","H","Wellness and salons"),
"NSE:MAKS":("W","ELECTRIC MOTORS & GENERATORS","M","Assembles DG sets; distributes auto spares"),
"NSE:POSITRON":("R","CITY GAS DISTRIBUTION","M","Gas distribution solutions and advisory"),
"NSE:AGNI":("W","RENEWABLE ENERGY EPC","H","Solar PV plant assembly and installation, not a power producer"),
"NSE:TRANSWIND":("R",None,"M","Official record says construction; not a power generator"),
"NSE:MAGSON":("K",None,"H","Retail chain"),
"NSE:GOYALSALT":("K",None,"H","Salt"),
"NSE:PELATRO":("K",None,"H","Customer engagement software"),
"NSE:PAR":("W","PHARMA APIS & INTERMEDIATES","M","APIs and fine chemicals"),
"NSE:RCDL":("K",None,"M","Castor derivatives"),
"NSE:SHIVAUM":("W","METAL TRADING","H","Trades iron and steel"),
"NSE:ANTGRAPHIC":("W","PACKAGING PRODUCTS","M","Paper-based packaging and publishing"),
"NSE:AARON":("W","MATERIAL HANDLING EQUIPMENT","H","Elevators and elevator parts"),
"NSE:ATMASTCO":("W","METAL FABRICATION & ENGINEERING","M","Steel trading plus engineering/erection"),
"NSE:HAPPY":("W","FORGINGS","H","Forged and machined transmission/driveline components"),
"NSE:NIRAJISPAT":("W","APPAREL MANUFACTURING","M","Polyester buttons (garment trims), no steel business"),
"NSE:PARIN":("W","FURNITURE & HOME PRODUCTS","H","Furniture"),
"NSE:SAGARDEEP":("W","COPPER","H","Copper and copper-alloy products"),
"NSE:RILINFRA":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Infra and civil construction, not pipes"),
"NSE:COMMITTED":("W","FREIGHT FORWARDING & LOGISTICS","H","Customs house broking and freight forwarding (not stockbroking)"),
"NSE:HOMESFY":("W","REAL ESTATE SERVICES","H","Real estate broking (not stockbroking)"),
"NSE:BEARDSELL":("K",None,"M","EPS products and prefab buildings"),
"NSE:ASPINWALL":("K",None,"M","Coffee processing/trading plus logistics"),
"NSE:JIWANRAM":("W","INDUSTRIAL SAFETY PRODUCTS","H","Leather safety gloves, coats"),
"NSE:UNIINFO":("W","TELECOM TOWERS & INFRASTRUCTURE","M","Telecom network services, not an operator"),
"NSE:LEXUS":("K",None,"H","Vitrified tiles"),
"NSE:PRAMARA":("W","ADVERTISING & MARKETING","M","Promotional merchandise"),
"NSE:AKIKO":("W","FINANCIAL PRODUCT DISTRIBUTION","H","Channel partner (DSA) for banks/NBFCs"),
"NSE:VISAMAN":("W","METAL TRADING","M","Trades steel pipes, structurals, coils"),
"NSE:VILAS":("K",None,"H","Components for T&D"),
"NSE:BEACON":("K",None,"H","Trustee services"),
"NSE:ELGIRUBCO":("W","INDUSTRIAL RUBBER PRODUCTS","M","Reclaimed rubber, retread rubber and machinery - not a tyre maker"),
"NSE:MASTER":("W","INDUSTRIAL PLASTICS & COMPOSITES","H","Plastic engineering components"),
"NSE:LRRPL":("W","INDUSTRIAL RUBBER PRODUCTS","H","Reclaimed rubber, not zinc/lead"),
}
