D = {
"BSE:COCHMAL":("K",None,"H","Tea and rubber plantations"),
"NSE:WILLAMAGOR":("W","INVESTMENT HOLDING COMPANIES","M","Investment and lending; no plantations of its own"),
"NSE:GTPL":("K",None,"H","Cable TV and broadband"),
"NSE:HATHWAY":("K",None,"H","Cable broadband"),
"NSE:NELCO":("K",None,"H","Satellite communication services"),
"BSE:CHOKSILA":("K",None,"H","Contract testing"),
"NSE:INDIANCARD":("K",None,"M","Card clothing"),
"NSE:GOLDENTOBC":("K",None,"M","Tobacco"),
"NSE:KOTHARIPRO":("R",None,"M","Real estate and international trade; no tobacco business now"),
"BSE:RAGHUTOB":("W","REAL ESTATE DEVELOPMENT","H","Real estate development"),
"NSE:ATLASCYCLE":("K",None,"M","Bicycles"),
"NSE:SWARAJENG":("K",None,"H","Tractor engines"),
"BSE:ALEXANDER":("K",None,"M","Philately/numismatics"),
"BSE:ASHRAM":("K",None,"M","Devotional products trading"),
"BSE:CEENIK":("W","APPAREL MANUFACTURING","M","Garment manufacturing plus property rental"),
"BSE:DITCO":("K",None,"M","Real estate, agency, distribution"),
"NSE:EKI":("K",None,"M","Carbon-credit trading and advisory"),
"BSE:FORBESCO":("R",None,"M","Precision tools/engineering, hygiene products, real estate - mixed"),
"BSE:GGL":("W","JEWELLERY RETAIL & MANUFACTURING","M","Diamonds and gold jewellery"),
"BSE:GUJINJEC":("K",None,"M","Trading after exiting pharma"),
"BSE:ZHEMHOLD":("W","INVESTMENT HOLDING COMPANIES","M","Investments and financing"),
"NSE:HEXATRADEX":("W","INVESTMENT HOLDING COMPANIES","M","Investment and finance (plus trading)"),
"BSE:JOSTS":("W","MATERIAL HANDLING EQUIPMENT","H","Material-handling and engineered products"),
"BSE:KINETRU":("W","DIVERSIFIED & OTHER LENDING","M","Loans and investments"),
"BSE:MOPSHOP":("K",None,"M","Facility-management supplies"),
"BSE:MCLTD":("K",None,"M","Mobile phone distribution"),
"BSE:PHOTOQUP":("W","LIGHTING & ELECTRICAL ACCESSORIES","M","Lighting for film/photography"),
"BSE:PROMACT":("K",None,"M","Manufacturing and trading"),
"BSE:PCL":("W","PACKAGED FOODS & FOOD PROCESSING","M","Cashew trading and processing"),
"BSE:SKRABUL":("W","JEWELLERY RETAIL & MANUFACTURING","M","Gems and jewellery (plus real estate)"),
"NSE:SMARTLINK":("W","INVESTMENT HOLDING COMPANIES","H","Investment company; earns mainly from investing"),
"BSE:ZSVARAJT":("K",None,"M","General trading"),
"BSE:SYMBIOX":("K",None,"M","Textile trading"),
"BSE:TIHIL":("K",None,"M","Export trading"),
"BSE:TRIOMERC":("K",None,"M","Trading"),
"BSE:UTIQUE":("K",None,"M","Precious metal trading"),
"NSE:WHBRADY":("K",None,"M","Engineering trading and rentals"),
"BSE:MHSGRMS":("K",None,"M","Passenger transport"),
"NSE:SKYWAYS":("W","FREIGHT FORWARDING & LOGISTICS","H","Air freight forwarding and logistics, not tourism"),
"NSE:FEL":("R",None,"M","Under insolvency (CIRP)"),
"BSE:GALACTICO":("W","STOCKBROKING & INVESTMENT BANKING","M","SEBI Category I merchant banker"),
"BSE:IFL":("W","TRADING & DISTRIBUTION","M","Paper and securities trading"),
"BSE:MORGAN":("W","DIVERSIFIED & OTHER LENDING","M","Fund-based financing activities"),
"BSE:CALCOM":("W","LIGHTING & ELECTRICAL ACCESSORIES","M","Lighting and electronics products manufacturer, not a broadcaster"),
"BSE:CATVISION":("W","TELECOM EQUIPMENT & OPTICAL FIBRE","M","Video/data equipment for cable networks"),
"BSE:DIKSAT":("K",None,"M","Satellite TV channel"),
"BSE:SHARPLINE":("W","ADVERTISING & MARKETING","M","Advertising and marketing solutions"),
"BSE:AUTOINT":("W","VEHICLE RENTAL & MOBILITY SERVICES","H","Self-drive and chauffeur car rental"),
"NSE:JKIPL":("W","TRADING & DISTRIBUTION","M","Export trader of construction machinery; no tyres"),
"NSE:MOTOGENFIN":("W","REAL ESTATE SERVICES","M","Leases property; no vehicle finance"),
"BSE:SAKTHIFIN":("K",None,"H","Vehicle finance"),
"NSE:GANECOS":("K",None,"H","PET recycling"),
"BSE:RESGEN":("K",None,"H","Plastic-waste pyrolysis"),
"BSE:AMANAYA":("R",None,"M","Commodity/securities trading and advisory"),
"NSE:AUGMONT":("W","PRECIOUS METALS","M","Gold/silver bullion platform, not watches"),
"BSE:NVENTURES":("W","JEWELLERY RETAIL & MANUFACTURING","M","Diamond trading"),
"BSE:RASANDIK":("W","AUTO COMPONENTS","M","Sheet-metal auto components and electric 3-wheelers"),
"NSE:BONLON":("K",None,"M","Non-ferrous metals, wires"),
"NSE:PACIFICI":("W","STONE & OTHER BUILDING MATERIALS","H","Granite and quartz slabs, no cables"),
"BSE:STML":("R",None,"M","Maintenance contracts and interior work"),
"NSE:VINDHYATEL":("K",None,"H","Cables plus EPC"),
"NSE:GFSTEELS":("W","TELECOM EQUIPMENT & OPTICAL FIBRE","M","Telecom and communication equipment; no zinc/lead"),
}
