D = {
"BSE:ARAVALIS":("K",None,"M","Capital-market services"),
"NSE:BLBLIMITED":("K",None,"M","Securities trading"),
"BSE:KIFS":("W","DIVERSIFIED & OTHER LENDING","M","Margin funding, loans against shares, IPO funding"),
"BSE:MSLGLOBAL":("W","TRADING & DISTRIBUTION","M","Trades goods and merchandise"),
"BSE:ZMULTIPU":("K",None,"M","Trading and investment"),
"BSE:OASISEC":("W","INVESTMENT HOLDING COMPANIES","M","Investments"),
"NSE:PNBGILTS":("K",None,"H","Primary dealer in government securities"),
"NSE:PALASHSECU":("R",None,"M","Investments plus food processing"),
"BSE:PEETISEC":("W","TRADING & DISTRIBUTION","M","Trades textiles and garments"),
"BSE:RRSECUR":("K",None,"M","Share/property trading"),
"BSE:RGF":("K",None,"M","Financial services"),
"BSE:RRFIN":("W","WEALTH MANAGEMENT","M","Financial, wealth-management and insurance services"),
"BSE:SANGAMFIN":("W","DIVERSIFIED & OTHER LENDING","M","NBFC business lending"),
"BSE:SHREESEC":("W","DIVERSIFIED & OTHER LENDING","M","Investing and financing"),
"BSE:SIDDHA":("K",None,"M","Share trading"),
"NSE:SONAL":("W","DIVERSIFIED & OTHER LENDING","H","NBFC short/long-term lending"),
"BSE:SUGALDAM":("K",None,"M","Share broking"),
"BSE:SWAGTAM":("R",None,"M","Real estate, consulting, jewellery/bullion trading"),
"BSE:SWRNASE":("W","REAL ESTATE SERVICES","M","Surrendered NBFC licence; now leases investment properties"),
"BSE:SYTIXSE":("K",None,"M","Financial-market services"),
"NSE:TEAMGTY":("W","INVESTMENT HOLDING COMPANIES","M","NBFC investing own funds"),
"BSE:TITANSEC":("W","DIVERSIFIED & OTHER LENDING","M","Loans and share dealing"),
"BSE:TRUSTWAVE":("K",None,"M","Advisory and recoveries"),
"BSE:VIKALPS":("K",None,"M","Share trading and finance"),
"BSE:VINTAGES":("K",None,"M","Financial services"),
"BSE:BRPL":("W","METAL FABRICATION & ENGINEERING","M","Pre-engineered buildings, roofing and cladding"),
"NSE:INDIANHUME":("W","WATER INFRASTRUCTURE & TREATMENT","M","Manufactures and lays water pipelines (water-infra EPC)"),
"NSE:SHANKARA":("W","STEEL PIPES & TUBES","M","After the retail demerger (now Shankara Buildpro), this entity makes precision steel tubes, CR strips and roofing"),
"NSE:BUILDPRO":("K",None,"M","Building-products retail"),
"NSE:DAVANGERE":("K",None,"H","Sugar"),
"NSE:EIDPARRY":("K",None,"H","Sugar, ethanol, nutraceuticals"),
"NSE:GODAVARIB":("K",None,"H","Ethanol and bio-chemicals"),
"BSE:SBECSYS":("K",None,"M","Sugar and bioenergy"),
"BSE:URSUGAR":("K",None,"M","Sugar services"),
"NSE:VETO":("W","WIRES CABLES & CONDUCTORS","M","Wires and cables (plus lighting, fans)"),
"BSE:KRIFILIND":("K",None,"M","HDPE/PP ropes"),
"BSE:MODIPON":("R",None,"M","Non-operating since 2007"),
"NSE:PARASPETRO":("R",None,"M","Manufacturing discontinued"),
"BSE:RAMGOPOLY":("W","TRADING & DISTRIBUTION","M","Commodity trading"),
"NSE:VIVIDHA":("K",None,"M","Textiles"),
"BSE:ACKNIT":("W","INDUSTRIAL SAFETY PRODUCTS","M","Industrial hand gloves (plus garments)"),
"BSE:SOUTLAT":("R",None,"M","No operations; rent and interest income only"),
"NSE:ASIANTNE":("K",None,"M","Tea and grain trading"),
"NSE:HALDER":("W","RICE & GRAIN PROCESSING","M","Rice trading/export"),
"NSE:HARRMALAYA":("K",None,"H","Tea and rubber plantations"),
"BSE:JGTL":("W","INDUSTRIAL AUTOMATION & INSTRUMENTATION","H","Electronic thickness gauges"),
"NSE:SHYAMTEL":("W","TRADING & DISTRIBUTION","M","Trades mobile accessories and appliances"),
"NSE:SURANAT&P":("W","RENEWABLE POWER GENERATION","M","Solar/wind power generation and solar products"),
"NSE:XTRANET":("W","IT SERVICES & CONSULTING","M","Cloud/IT transformation services"),
"BSE:HATHWAYB":("K",None,"M","Cable TV"),
}
