D = {
"BSE:ESCORP":("K",None,"H","Portfolio management services"),
"BSE:KIDUJA":("W","INVESTMENT HOLDING COMPANIES","M","Investments and dealing in shares; no fund management"),
"BSE:MIDEASTP":("K",None,"M","Investment services to NRIs"),
"BSE:BCCFUBA":("W","ELECTRONIC COMPONENTS & MATERIALS","H","Printed circuit boards maker (auto is one end-market)"),
"BSE:ENTRINT":("W","TRADING & DISTRIBUTION","M","Trades textiles, auto parts, fruit and nuts"),
"BSE:GRAVITY":("W","HOME TEXTILES","H","Furnishing fabrics manufacturer"),
"NSE:IMPAL":("K",None,"M","Auto replacement-parts distributor"),
"BSE:MKPMOB":("R",None,"M","Official record only says 'manufacturing and trading activities'"),
"BSE:SIDH":("W","DIVERSIFIED & OTHER LENDING","H","NBFC financing/investment - not a dealership"),
"NSE:AZADIND":("R",None,"M","Official record: steel bars; name suggests a mobility pivot - confirm current business"),
"NSE:MERCURYEV":("W","ELECTRIC MOBILITY & CHARGING","M","Makes and trades electric vehicles"),
"NSE:ROSSTECH":("W","AEROSPACE & DEFENCE MANUFACTURING","H","Aerospace and defence electronics/harnesses, not auto"),
"BSE:AURIQUE":("W","AGRICULTURE & COMMODITY TRADING","M","Processing and trading of agricultural commodities"),
"NSE:NILE":("W","METAL RECYCLING","H","Secondary (recycled) lead producer - same bucket as Gravita/Pondy Oxides"),
"BSE:PANCARBON":("W","GRAPHITE & CARBON MATERIALS","M","Carbon rods (input for dry cells), not batteries"),
"BSE:STDBAT":("W","METAL TRADING","M","Now deals in steel and metals; no battery business"),
"BSE:WAAREE":("K",None,"M","Trades EVs and lithium batteries"),
"NSE:KOTYARK":("K",None,"H","Bio-diesel"),
"BSE:TRUEGREEN":("K",None,"H","Grain ethanol"),
"BSE:EMMESSA":("W","NUTRACEUTICALS & CONSUMER HEALTH","M","Small ayurvedic/health-products portfolio plus property leasing"),
"BSE:HINDBIO":("W","PHARMA FORMULATIONS","M","Manufactures/sells pharmaceutical products"),
"BSE:INDRANIB":("W","DIVERSIFIED BUSINESSES","M","Foods & hospitality, engineering and healthcare"),
"BSE:KOBO":("W","PHARMA FORMULATIONS","M","Pharmaceutical business"),
"BSE:NATURAL":("W","AGRICULTURE & COMMODITY TRADING","H","Trades agricultural produce"),
"BSE:SCAGRO":("W","AGRICULTURE & COMMODITY TRADING","M","Agriculture, horticulture, organic farming"),
"BSE:TRABI":("K",None,"M","Biotech R&D"),
"NSE:ELECTHERM":("W","STEEL & IRON","M","Special steel is the bulk of revenue; also induction furnaces and EVs"),
"BSE:GARGFUR":("W","STEEL & IRON","H","Iron and steel products"),
"BSE:GLOBUSCON":("W","POWER GENERATION & INTEGRATED UTILITIES","M","Power generation/distribution"),
"NSE:ISGEC":("K",None,"H","Heavy engineering: boilers, process plant, EPC"),
"BSE:INDCTST":("W","METAL RECYCLING","M","Ship breaking and trading"),
"BSE:HOM":("W","RENEWABLE ENERGY SOLUTIONS","M","Renewable energy business"),
"BSE:SAMSRITA":("R",None,"M","Healthcare services/diagnostics/biotech R&D - not outsourcing"),
"NSE:ASHOKAMET":("W","METAL TRADING","H","Trades steel"),
"NSE:FOSECOIND":("W","SPECIALTY CHEMICALS","M","Supplies consumables/additives to foundries; it is not a foundry"),
"BSE:FFPL":("W","COAL & COKE","H","Low-ash metallurgical coke"),
"BSE:LATIMMETAL":("W","STEEL & IRON","M","Steel products trading/manufacturing plus real estate"),
"BSE:SHRIGANG":("W","ALCOHOLIC BEVERAGES","H","Makes IMFL (liquor)"),
"NSE:INCREDIBLE":("W","STEEL & IRON","H","Iron and steel rolled products"),
"NSE:KESORAMIND":("W","SYNTHETIC FIBRES & YARNS","H","Cement business demerged into UltraTech (2025); remaining business is rayon, transparent paper and chemicals"),
"NSE:NIRAJ":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Infrastructure contractor, not a cement maker"),
"NSE:BLACKROSE":("K",None,"M","Chemical manufacturing and distribution"),
"BSE:CROPSTER":("W","AGRICULTURE & COMMODITY TRADING","H","Trades agricultural products"),
"BSE:INDXTRA":("K",None,"M","Warehousing plus chemicals trading"),
"BSE:KUBERJI":("W","DIVERSIFIED & OTHER LENDING","H","NBFC"),
"BSE:PADMAIND":("W","AGRICULTURE & COMMODITY TRADING","H","Agri trading"),
"BSE:SAWACA":("W","TRADING & DISTRIBUTION","M","Trades machinery, metal scrap and cotton bales"),
"NSE:STALLION":("K",None,"M","Sells refrigerant and industrial gases"),
"NSE:DCW":("K",None,"H","Caustic soda, PVC, SIOP"),
"NSE:DENORA":("R","INDUSTRIAL MACHINERY","M","Makes electrolysis electrodes/equipment used by chlor-alkali plants; not a chlor-alkali producer"),
"NSE:KANORICHEM":("W","ALCOHOL & SOLVENT CHEMICALS","M","Alco-chemicals, formaldehyde, pentaerythritol; exited chlor-alkali in 2011"),
"BSE:RANDER":("W","DIVERSIFIED & OTHER LENDING","M","Financing and securities trading"),
"BSE:SABOOSOD":("W","SALT","M","Salt manufacturer (plus hotel/FMCG)"),
"BSE:CPML":("W","FILM MUSIC & CONTENT","M","OTT / digital-content business; no multiplex operations"),
"BSE:VISIONCINE":("W","FILM MUSIC & CONTENT","M","Produces advertisement films"),
"NSE:FABTECH":("K",None,"H","Biopharma cleanroom engineering"),
"BSE:HEMANG":("K",None,"M","Coal trading"),
"BSE:MRP":("W","AGRICULTURE & COMMODITY TRADING","H","Processing and trading of agro commodities"),
"BSE:WOMENNET":("K",None,"M","Coal supply"),
"NSE:REFEX":("K",None,"M","Coal procurement/ash handling plus refrigerant gases"),
"BSE:VIRYA":("R",None,"M","Near-dormant"),
"NSE:ATALREAL":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Civil contractor, no cold chain"),
"BSE:KCSL":("K",None,"H","Cold storage rental"),
"BSE:TCIIND":("W","REAL ESTATE SERVICES","M","Rents property as film/TV shooting space"),
"NSE:A2ZINFRA":("K",None,"M","Engineering and maintenance services"),
"BSE:ABHIINFRA":("K",None,"M","Construction"),
"BSE:ACROW":("R",None,"M","Textiles and real estate - not construction EPC"),
"BSE:ADHBHUTIN":("W","REAL ESTATE DEVELOPMENT","H","Real estate business"),
"BSE:ANNAINFRA":("W","REAL ESTATE DEVELOPMENT","H","Land for real estate development"),
"NSE:ARIS":("W","TRADING & DISTRIBUTION","M","Tech-enabled supplier of construction materials; revenue is material sales, not contracting"),
"BSE:ATHCON":("K",None,"M","Construction advisory"),
"BSE:CEMAINFRA":("K",None,"M","Residential construction"),
"NSE:CCCL":("K",None,"H","Turnkey construction"),
"BSE:CONSTRONIC":("K",None,"M","Construction services"),
"BSE:CRANEINFRA":("W","REAL ESTATE DEVELOPMENT","M","Builds apartments/houses for sale"),
"NSE:DHARAN":("K",None,"M","Real estate plus EPC"),
"BSE:EXPOEAPL":("W","HEAT EXCHANGERS & PROCESS EQUIPMENT","H","Pressure vessels, columns and towers"),
"BSE:FRASER":("K",None,"M","Construction-site products"),
"BSE:GARNET":("W","REAL ESTATE DEVELOPMENT","H","Real estate developer"),
"NSE:GENCON":("K",None,"H","Civil construction"),
"BSE:JAINCO":("W","DIVERSIFIED & OTHER LENDING","M","Investments and lending"),
"NSE:KPEL":("W","RENEWABLE ENERGY EPC","H","Wind-farm balance-of-plant developer/EPC"),
"BSE:KRETTOSYS":("R",None,"M","Software development plus real estate"),
"BSE:MTPL":("W","GOLD FINANCE","M","Gold financing and lending"),
"BSE:NEOINFRA":("W","REAL ESTATE DEVELOPMENT","H","Real estate development"),
"BSE:RJSHAH":("K",None,"M","Engineering and construction"),
"BSE:SBLI":("W","REAL ESTATE DEVELOPMENT","H","Real estate development"),
"BSE:SISL":("K",None,"M","Construction contracts"),
"BSE:SHARIKA":("W","POWER T&D EPC","M","Project execution in the power sector"),
"BSE:SKIFL":("W","REAL ESTATE DEVELOPMENT","H","Real estate development"),
"BSE:SHRISTI":("W","REAL ESTATE DEVELOPMENT","H","Real estate developer"),
"BSE:TATIAGLOB":("R",None,"M","Textiles plus infrastructure projects"),
"BSE:TPROJECT":("W","DIVERSIFIED & OTHER LENDING","M","Investing and financing"),
"BSE:UTLINDS":("R",None,"M","IT support plus building construction"),
"BSE:VASINFRA":("W","REAL ESTATE DEVELOPMENT","H","Real estate development"),
"NSE:VASCONEQ":("K",None,"H","EPC plus real estate"),
"BSE:VISVEN":("K",None,"M","Civil construction projects"),
"BSE:WAGEND":("W","INVESTMENT HOLDING COMPANIES","M","Primarily investing activities"),
"NSE:SANGHVIMOV":("K",None,"H","Crane rental"),
}
