D = {
"BSE:THAKKERS":("K",None,"M","Hospitality, real estate, construction"),
"NSE:UMIYA_MRO":("R",None,"M","Networking equipment plus real estate - mixed"),
"BSE:GSLTD":("K",None,"H","Supermarket chain"),
"BSE:NEELKANTH":("K",None,"M","Rice trading"),
"NSE:VGL":("R",None,"M","Ex-Aarvee Denims pivoting after 2024-25 control change - confirm new business"),
"NSE:BRNL":("K",None,"H","Road BOT"),
"NSE:IL&FSTRANS":("K",None,"H","Road assets"),
"NSE:SADBHIN":("K",None,"H","BOT/annuity roads"),
"NSE:KAUSHALYA":("K",None,"M","Construction contracts"),
"NSE:AVANTIFEED":("K",None,"H","Shrimp feed and processing"),
"NSE:MUKKA":("K",None,"H","Fish meal and fish oil"),
"BSE:MPFSL":("W","RENEWABLE ENERGY SOLUTIONS","M","Green energy business; no security equipment"),
"BSE:MSECL":("W","ENGINEERING CONSULTANCY","H","Civil engineering consultancy and surveying"),
"NSE:NOVAAGRI":("K",None,"H","Agri inputs"),
"NSE:AQYLON":("R",None,"M","Ex-Sri Adhikari Brothers TV; post-insolvency pivot - confirm semiconductor activity"),
"NSE:ACCURACY":("W","FREIGHT FORWARDING & LOGISTICS","M","Third-party logistics; does not own ships"),
"NSE:THACKER":("W","INVESTMENT HOLDING COMPANIES","M","Real estate and financial activities; no shipping"),
"BSE:AERPACE":("R",None,"M","Renewable energy and infrastructure - confirm module manufacturing"),
"NSE:INA":("K",None,"H","Solar modules"),
"NSE:ONIXSOLAR":("K",None,"M","Renewable energy solutions"),
"NSE:SOLARWORLD":("W","RENEWABLE ENERGY EPC","H","Solar EPC, not a cell/module maker"),
"BSE:BETXIND":("W","FABRICS & TEXTILE PROCESSING","H","Art-silk cloth processing (job work)"),
"BSE:BIOGEN":("W","INVESTMENT HOLDING COMPANIES","M","Trading in shares"),
"NSE:DCM":("W","DIVERSIFIED BUSINESSES","M","Grey-iron castings, textiles, IT infrastructure services, real estate"),
"NSE:DCMSRIND":("W","SUGAR & INTEGRATED ETHANOL","M","Primarily sugar, alcohol and power"),
"NSE:GANESHBE":("W","PORTS & TERMINALS","M","Bulk-liquid port storage terminals (plus some specialty chemicals)"),
"NSE:GODREJIND":("K",None,"H","Oleochemicals plus group holding"),
"NSE:INDIAGLYCO":("K",None,"H","Bio-based chemicals"),
"NSE:IWP":("W","PACKAGED FOODS & FOOD PROCESSING","M","Katha, processed gambier and spices"),
"NSE:KINGFA":("W","INDUSTRIAL PLASTICS & COMPOSITES","M","Modified plastic compounds"),
"BSE:LACTOSE":("W","PHARMA EXCIPIENTS","M","Pharma lactose/excipients and job work"),
"BSE:MADHUDIN":("W","REAL ESTATE SERVICES","M","Renting of properties"),
"NSE:MANGALAM":("W","PHARMA APIS & INTERMEDIATES","H","APIs and intermediates"),
"BSE:MITSU":("W","INDUSTRIAL PLASTICS & COMPOSITES","M","Blow/injection-moulded plastic products"),
"BSE:NATHIND":("W","PAPER & PAPERBOARD","M","Industrial and specialty papers"),
"NSE:ORICONENT":("R",None,"M","Closures/preforms, petrochemicals, colorants, real estate - mixed"),
"BSE:PHYCHEM":("W","INDUSTRIAL PLASTICS & COMPOSITES","M","Roto-moulding polymer compounds"),
"NSE:RAJSREESUG":("W","SUGAR & INTEGRATED ETHANOL","H","Sugar, distillery, power"),
"NSE:RESPONIND":("W","INDUSTRIAL PLASTICS & COMPOSITES","M","PVC flooring, leathercloth and ropes"),
"BSE:RISHIROOP":("K",None,"M","Polymers and compounds"),
"BSE:ROOPAIND":("K",None,"M","Triphenylphosphine chemistry"),
"BSE:SAMRATPH":("K",None,"M","Chemicals"),
"NSE:SGRL":("K",None,"M","Pharma intermediates and fine chemicals"),
"BSE:SOUTHMG":("W","NON-FERROUS METALS","M","Magnesium metal"),
"BSE:SWADHATURE":("R",None,"M","Agri produce, chemicals, natural extracts"),
"BSE:SYSCHEM":("W","PHARMA APIS & INTERMEDIATES","H","APIs and bulk drugs"),
"BSE:TAKE":("W","PHARMA CONTRACT RESEARCH & MANUFACTURING","M","Life-sciences clinical/regulatory services"),
"BSE:UNIQUEO":("W","PACKAGED FOODS & FOOD PROCESSING","M","Feed and food products exporter"),
"NSE:VINYLINDIA":("W","CHEMICAL DISTRIBUTION","H","Trades vinyl acetate monomer"),
"NSE:VIVIMEDLAB":("W","PHARMA APIS & INTERMEDIATES","M","APIs, CDMO and formulations; specialty chemicals now minor"),
"BSE:AARCON":("K",None,"M","Hotel/restaurant management"),
"BSE:KBSINDIA":("W","STOCKBROKING & INVESTMENT BANKING","H","Stock broking"),
"BSE:LELAVOIR":("W","PERSONAL & HOME SERVICES","M","Laundry services"),
"BSE:RESPONSINF":("W","IT SERVICES & CONSULTING","M","IT consulting, SaaS, talent solutions"),
"BSE:WORKMATES":("W","IT SERVICES & CONSULTING","H","AWS cloud consulting partner"),
"BSE:SPITZE":("W","BUILDING HARDWARE","M","Modular kitchen and wardrobe fittings"),
"BSE:CHENFERRO":("W","COAL & COKE","M","Coal trading"),
"BSE:DIVSHKT":("W","STONE & OTHER BUILDING MATERIALS","H","Quartz slabs and tiles"),
"BSE:EASTINDIA":("W","GAS CYLINDERS & CONTAINERS","M","Industrial steel barrels"),
"BSE:GTIL":("W","STEEL WIRE & WIRE ROPES","M","Steel-wire gabions and geosynthetics"),
"NSE:KRIDHANINF":("W","METAL TRADING","M","Iron and steel trading"),
"BSE:KRISHNA":("W","METAL FABRICATION & ENGINEERING","M","Steel fabrication, solar structures, PEB, HVAC"),
"NSE:LLOYDSME":("K",None,"H","Iron ore mining, sponge iron, pellets"),
"BSE:MAGNUS":("R",None,"M","Official record: agro-products trading"),
"BSE:MPCOSEMB":("W","IT SERVICES & CONSULTING","M","Now IT/ITES services"),
"NSE:PENIND":("W","METAL FABRICATION & ENGINEERING","M","Precision engineering products, PEB, hydraulics"),
"NSE:PITTIENG":("W","METAL FABRICATION & ENGINEERING","M","Electrical-steel laminations, motor cores and machining for motor/generator OEMs - does not make steel"),
"BSE:SALAUTO":("W","AUTO COMPONENTS","H","Automotive components"),
"BSE:SRUSTEELS":("W","METAL TRADING","M","Stainless steel trading"),
"BSE:SPECTRA":("R",None,"M","Operations closed; nil revenue"),
"NSE:STLSTRINF":("W","REAL ESTATE DEVELOPMENT","H","Real estate"),
"BSE:TELGE":("W","ENGINEERING CONSULTANCY","M","Engineering design services"),
"BSE:VMS":("W","METAL RECYCLING","H","Ship breaking and metal trading"),
"BSE:YASHRAJC":("W","GAS CYLINDERS & CONTAINERS","M","Steel drums and barrels"),
"BSE:ARCEEIN":("K",None,"M","PVC and steel pipes"),
"NSE:NATIONSTD":("W","REAL ESTATE DEVELOPMENT","H","Real estate development (Lodha subsidiary)"),
"NSE:RAJRATAN":("K",None,"H","Tyre bead wire"),
"BSE:SHALIWIR":("K",None,"M","Wires"),
"NSE:AKCAPIT":("K",None,"H","Merchant banker"),
"NSE:AFSL":("K",None,"M","Broking and allied"),
"BSE:AMRAPLIN":("K",None,"M","Bullion/share trading"),
"BSE:ARISE":("W","DIVERSIFIED & OTHER LENDING","M","Investments and loan financing"),
"BSE:ARYACAPM":("K",None,"M","Market making and proprietary investment"),
"NSE:ARYAMAN":("K",None,"H","Merchant banking"),
"NSE:ASHIKAG":("K",None,"M","Financial-services group holding"),
"BSE:BAMPSL":("K",None,"M","Securities dealing"),
"BSE:BERYLSE":("W","DIVERSIFIED & OTHER LENDING","M","Finance and investment"),
"BSE:CILSEC":("K",None,"M","Broking/financial services"),
"NSE:CHOICEIN":("K",None,"H","Broking and investment banking"),
"BSE:CSL":("W","DIVERSIFIED & OTHER LENDING","H","Loans to small retail borrowers"),
"BSE:EASUN":("W","DIVERSIFIED & OTHER LENDING","M","Financing and investment"),
"BSE:FUTURSEC":("W","DIVERSIFIED & OTHER LENDING","M","Finance"),
"BSE:GSLSEC":("W","DIVERSIFIED & OTHER LENDING","M","Finance"),
"BSE:GLOBALCA":("W","DIVERSIFIED & OTHER LENDING","M","Finance and investments"),
"NSE:HAMPTON":("W","REAL ESTATE DEVELOPMENT","M","Real estate (plus textiles, share trading)"),
"BSE:INDIANVSH":("K",None,"M","Investing and stressed assets"),
"BSE:ICSL":("W","TRUSTEESHIP & CORPORATE ADVISORY","M","Business structuring/restructuring advisory"),
"BSE:JAGSONSER":("K",None,"M","Equity/commodity trading"),
"NSE:KJMCFIN":("W","DIVERSIFIED & OTHER LENDING","M","Lending"),
"NSE:LADDERUP":("W","DIVERSIFIED & OTHER LENDING","M","Primarily financing"),
}
