D = {
"BSE:YOGISUNG":("K",None,"H","Construction and infra projects"),
"BSE:VIRATCRA":("W","DAIRY","H","Milk and dairy products; no cranes"),
"NSE:BOROSCI":("W","GLASS","M","Scientific/laboratory glassware and instruments"),
"BSE:KALPACOMME":("W","TRADING & DISTRIBUTION","M","Trades fabrics"),
"NSE:LAOPALA":("K",None,"M","Opal/glass tableware (houseware)"),
"NSE:MICEL":("K",None,"M","LED, medical appliances, EVs"),
"BSE:PROCLB":("W","TRAVEL & TOURISM","M","Air ticketing, tour operator, money changer"),
"BSE:QRIL":("K",None,"M","RO water products"),
"BSE:SALORAINTL":("K",None,"H","Consumer electronics"),
"BSE:ABVL":("K",None,"M","Co-packing services"),
"NSE:JINDALPHOT":("W","INVESTMENT HOLDING COMPANIES","H","Holds investments in group companies"),
"BSE:SBRANDS":("W","PERSONAL & HOME SERVICES","M","Spa services and branding"),
"BSE:SHRYDUS":("R",None,"M","Healthcare, pharma, real estate, green energy - unclear core"),
"BSE:SUNRETAIL":("W","EDIBLE OILS","M","Trades refined edible oils"),
"NSE:VAKRANGEE":("R","PAYMENTS & FINTECH","M","Assisted last-mile kendras: banking correspondent, ATM, e-commerce, bullion"),
"BSE:ANTARIKSH":("W","REAL ESTATE DEVELOPMENT","M","Real estate and construction-material trading"),
"BSE:CELLA":("K",None,"M","Logistics operations"),
"BSE:LAKSHMIEW":("R",None,"M","Official record describes loom spares; name says warehousing - confirm current revenue"),
"BSE:RLF":("W","FABRICS & TEXTILE PROCESSING","M","Textiles and embroidery"),
"BSE:PALCO":("W","ALUMINIUM","M","Aluminium products, not copper"),
"BSE:CEETAIN":("W","PACKAGED FOODS & FOOD PROCESSING","H","Food products manufacturer"),
"BSE:CHOKSI":("W","MEDICAL DEVICES & SUPPLIES","H","Medical X-ray films and healthcare supplies"),
"BSE:CYBELEIND":("W","WIRES CABLES & CONDUCTORS","H","Cables and wiring harness"),
"BSE:DHANCOT":("W","INVESTMENT HOLDING COMPANIES","M","Deals in securities and investments"),
"NSE:LAHOTIOV":("K",None,"M","Yarn merchant exporter"),
"NSE:NGIL":("W","PACKAGED FOODS & FOOD PROCESSING","M","Tutti-frutti manufacturing plus agri trading"),
"NSE:POLYSPIN":("W","PACKAGING PRODUCTS","H","FIBC (jumbo) bags"),
"BSE:SPARKLEGR":("R",None,"M","Mining, gold/jewellery, real estate - unclear core"),
"BSE:SUNILTX":("K",None,"M","Textiles"),
"BSE:YARNSYN":("K",None,"M","Textiles"),
"NSE:CRISIL":("K",None,"H","Ratings and research"),
"BSE:GSTL":("R",None,"M","Technology-enabled solutions; no evidence of cybersecurity focus"),
"BSE:GRAMEVA":("W","AGRICULTURE & COMMODITY TRADING","M","Agricultural products and handicrafts"),
"BSE:POLSON":("W","SPECIALTY CHEMICALS","H","Leather tanning chemicals; no dairy business"),
"NSE:URAVIDEF":("K",None,"M","Defence equipment plus auto lamps"),
"BSE:CHLLTD":("W","HOTELS & RESORTS","H","Runs a five-star hotel"),
"NSE:MOLBIO":("W","MEDICAL DEVICES & SUPPLIES","M","Point-of-care diagnostic devices/kits (product maker, not a lab chain)"),
"BSE:BEEYU":("W","TEA & COFFEE","H","Tea plantations"),
"NSE:COMFINTE":("W","ALCOHOLIC BEVERAGES","M","Liquor manufacturing plus trading"),
"BSE:DHARNI":("K",None,"M","Financial services"),
"BSE:EKAMLEA":("K",None,"M","Investment and finance"),
"BSE:ELNET":("W","REAL ESTATE SERVICES","M","Owns/operates an IT/BPO technology park"),
"BSE:ENBETRD":("K",None,"M","Financial services"),
"BSE:ESARIND":("K",None,"M","Asset finance"),
"BSE:EXPLICITFIN":("K",None,"M","Finance and investment"),
"BSE:FERVENTSYN":("K",None,"M","Food and finance"),
"BSE:FRONTCAP":("K",None,"H","Loans and advances"),
"BSE:GOGIACAPGL":("W","STOCKBROKING & INVESTMENT BANKING","H","Broking and dealing in securities"),
"BSE:GOLECHA":("K",None,"H","Lending"),
"BSE:GREENCREST":("K",None,"M","Finance and investments"),
"NSE:HEALTHX":("W","PHARMA DISTRIBUTION & RETAIL","M","Formerly SastaSundar: digital healthcare/pharmacy network"),
"BSE:HINDAPL":("W","INVESTMENT HOLDING COMPANIES","M","Investment activities"),
"NSE:HYBRIDFIN":("W","STOCKBROKING & INVESTMENT BANKING","H","Stock broking"),
"NSE:ICDSLTD":("K",None,"M","Financial services and rentals"),
"BSE:IFINSER":("W","STOCKBROKING & INVESTMENT BANKING","H","Merchant banking"),
"BSE:INVIGO":("W","PROFESSIONAL & BUSINESS SERVICES","M","Advisory/counselling services"),
"BSE:LERTHAI":("K",None,"M","Finance and investments"),
"BSE:MFSINTRCRP":("W","METAL FABRICATION & ENGINEERING","H","Precision steel fabrication and industrial sheds"),
"BSE:MADALA":("R","REAL ESTATE SERVICES","M","Formerly Softsol India: IT services plus leasing of property - confirm split"),
"BSE:MAHANIN":("K",None,"M","Financing and investment"),
"NSE:MAJESAUT":("W","REAL ESTATE SERVICES","M","Leases property and provides maintenance services"),
"BSE:MEFCOMCAP":("W","STOCKBROKING & INVESTMENT BANKING","H","Capital-market operations and merchant banking"),
"NSE:MERCANTILE":("R",None,"M","Property leasing plus manpower supply"),
"BSE:ZMILGFIN":("K",None,"M","Loans and advances"),
"NSE:ONELIFECAP":("W","INVESTMENT HOLDING COMPANIES","M","Invests in companies"),
"NSE:PTL":("R",None,"M","Leases its tyre plant (to Apollo Tyres); lessor, not a lender"),
"BSE:PREMCAP":("W","TRADING & DISTRIBUTION","M","Trades dairy products"),
"BSE:PROFINC":("K",None,"M","Financial and capital-market services"),
"NSE:RIIL":("R",None,"M","Operates product pipelines and industrial infrastructure for Reliance - not a lender"),
"NSE:SVGLOBAL":("W","REAL ESTATE DEVELOPMENT","H","Real estate"),
"BSE:SICAPIT":("W","FOREIGN EXCHANGE & REMITTANCES","H","Full-fledged money changer"),
"BSE:SPCAPIT":("K",None,"M","Finance and investment"),
"NSE:SAICAPI":("W","INVESTMENT HOLDING COMPANIES","M","Deals in securities"),
"BSE:SAINIK":("K",None,"M","Investment and finance"),
"NSE:SAMMAANCAP":("W","HOUSING FINANCE","H","NHB-registered housing finance company (ex-Indiabulls Housing Finance)"),
"BSE:SANCF":("W","STOCKBROKING & INVESTMENT BANKING","M","Broking in cash and derivatives"),
"BSE:SHVFL":("K",None,"M","Trading and finance"),
"BSE:TASHIND":("K",None,"H","NBFC lending"),
"BSE:TRANSFRE":("W","INVESTMENT HOLDING COMPANIES","M","Former container maker; now earns from deposits/investments"),
"BSE:UNTTEMI":("W","FABRICS & TEXTILE PROCESSING","M","Embroidered fabrics"),
"BSE:VEDANTASSET":("W","PAYMENTS & FINTECH","M","Banking correspondent services"),
"BSE:WALLFORT":("W","STOCKBROKING & INVESTMENT BANKING","H","Stock broking"),
"NSE:ADANIENT":("K",None,"H","Conglomerate incubator"),
"NSE:AMBALALSA":("K",None,"M","Pharma and electronics"),
"NSE:ATLANTAA":("W","ROAD CONSTRUCTION","M","Road construction/BOT"),
"BSE:BALGOPAL":("R",None,"M","Transitioning from trading to real estate"),
"BSE:BGDL":("R",None,"M","Vague 'global trade facilitation'"),
"NSE:BMWVENTLTD":("K",None,"M","Steel distribution, tractor engines, PVC pipes"),
"BSE:CIANAGRO":("K",None,"M","Agro, healthcare, infra"),
"NSE:DCMSIL":("K",None,"H","Fibres, containers, defence, engineering"),
"BSE:DHOOTIN":("W","INVESTMENT HOLDING COMPANIES","M","NBFC deploying capital in investments"),
"BSE:DGL":("W","PLYWOOD LAMINATES & BOARDS","M","Timber trading and veneer sheets"),
"NSE:ELPROINTL":("K",None,"M","Surge arresters, real estate, investments"),
"NSE:FEDDERSHOL":("W","INVESTMENT HOLDING COMPANIES","M","Investment, finance, consultancy"),
"BSE:FRUTION":("R",None,"M","Consumer goods - unclear"),
"BSE:GTV":("W","METAL FABRICATION & ENGINEERING","H","High-tech steel fabrication"),
"NSE:GRASIM":("K",None,"H","Conglomerate: VSF, chemicals, cement, paints, financial services"),
"NSE:IBULLSLTD":("K",None,"M","Real estate and financial services"),
"NSE:ESSENTIA":("K",None,"M","Food, textiles, infra"),
"NSE:JAICORPLTD":("K",None,"H","Steel, plastics, yarn, real estate"),
}
