D = {
"NSE:KDGREEN":("R",None,"M","Renamed from Manbro Industries; official record says food & beverages - confirm"),
"NSE:KOTIC":("K",None,"M","Fertilisers, FMCG, healthcare"),
"NSE:LLOYDSENT":("R","INVESTMENT HOLDING COMPANIES","M","Steel trading plus large holding in Lloyds Metals"),
"NSE:MCCHRLS_B":("K",None,"M","Wind power plus commercial property"),
"NSE:MMWL":("R",None,"M","Mobile/digital value-added services"),
"BSE:MEGACOR":("W","DIVERSIFIED & OTHER LENDING","M","Investments and lending"),
"BSE:MENAMANI":("K",None,"M","Biofuel, construction, IT"),
"NSE:MODISONLTD":("W","ELECTRONIC COMPONENTS & MATERIALS","M","Electrical contacts (silver-alloy) for LV/MV/HV switchgear"),
"BSE:NAGPI":("W","FERRO ALLOYS","H","Ferro-manganese / silico-manganese"),
"NSE:NAHARINDUS":("K",None,"M","Textiles and sugar"),
"NSE:NAVA":("K",None,"H","Ferro alloys, power, mining, other"),
"BSE:OIVL":("W","AGRICULTURE & COMMODITY TRADING","M","Trades rice, pulses, grains"),
"BSE:PQIF":("K",None,"M","Trading-led group"),
"NSE:PRSMJOHNSN":("K",None,"M","Cement, RMC, tiles"),
"BSE:QUANTDIA":("K",None,"M","Mixed small businesses"),
"NSE:RTNINDIA":("K",None,"M","E-commerce, EVs, drones"),
"NSE:RELIANCE":("K",None,"H","Conglomerate"),
"NSE:SAB":("W","REAL ESTATE DEVELOPMENT","M","Construction and real estate"),
"NSE:SBC":("K",None,"M","Garments, manpower, tours"),
"NSE:SICAGEN":("K",None,"M","Building-material trading, power systems, barrels"),
"NSE:SIGIND":("K",None,"M","Polymer trading plus irrigation pipes"),
"BSE:SPICEISLIN":("K",None,"M","Textiles plus other"),
"BSE:STARSOURCE":("R",None,"M","Disposed pharma business - shell"),
"NSE:SWANCORP":("K",None,"H","Diversified parent (per your own grouping note)"),
"NSE:TIIL":("K",None,"H","Drum closures, scaffolding, textiles"),
"NSE:VIKASLIFE":("K",None,"M","Polymer trading and compounds"),
"BSE:YSL":("W","INVESTMENT HOLDING COMPANIES","M","Goods trading; value is mainly its holding in ISGEC"),
"BSE:SAICOM":("W","TRADING & DISTRIBUTION","M","Wholesale trading"),
"BSE:DRONACHRYA":("K",None,"H","Drone solutions"),
"BSE:NIKSTECH":("K",None,"M","Software plus drone trading"),
"BSE:SPACEINCUBA":("R",None,"M","Official record: textiles and general trading - confirm space-tech activity"),
"BSE:ZBINTXPP":("W","FABRICS & TEXTILE PROCESSING","M","Sells fabrics/textiles; no dyes"),
"BSE:JATTAINDUS":("W","AGRICULTURE & COMMODITY TRADING","H","Agro-commodity trader after selling yarn plant"),
"BSE:KRYPTONQ":("W","AUTO COMPONENTS","M","Tyres, rims, wheels; hospital equipment"),
"BSE:NATHUEC":("W","PROFESSIONAL & BUSINESS SERVICES","M","Management consultancy"),
"NSE:WEIZMANIND":("W","FABRICS & TEXTILE PROCESSING","H","Textile processing and job work"),
"BSE:EPUJA":("K",None,"M","Online puja portal"),
"NSE:MSTCLTD":("K",None,"H","E-auction platform"),
"BSE:MITSHI":("W","AGRICULTURE & COMMODITY TRADING","M","Agri products trading"),
"BSE:TILAK":("R",None,"M","Trading and financing"),
"NSE:ANIKINDS":("W","DIVERSIFIED BUSINESSES","M","Trading, real estate, mining - no longer an edible-oil processor"),
"NSE:DAMODARIND":("W","COTTON & BLENDED YARN","H","Cotton and fancy yarn"),
"BSE:KANELIND":("K",None,"M","Bulk edible-oil trading"),
"NSE:OSWALAGRO":("W","REAL ESTATE DEVELOPMENT","M","Real estate development and trading; no edible oil"),
"BSE:REGENTRP":("K",None,"M","Edible oil"),
"NSE:CRIZAC":("K",None,"H","Student recruitment platform"),
"NSE:EXCELSOFT":("K",None,"M","Digital learning SaaS"),
"BSE:JOINTECAED":("K",None,"M","Education IT"),
"BSE:AMTL":("K",None,"H","Energy meters"),
}
