D = {
"BSE:AMPVOLTS":("K",None,"H","EV chargers"),
"NSE:BGRENERGY":("W","BOILERS TURBINES & POWER EQUIPMENT","M","Power-plant systems and turnkey engineering contracts"),
"BSE:CLASELE":("W","DIVERSIFIED & OTHER LENDING","M","Finance and leasing; not trading on TradingView's scanner (likely suspended)"),
"NSE:HAVELLS":("W","CONSUMER APPLIANCES & ELECTRONICS","M","Fast-moving electrical goods; its peers Crompton, V-Guard and Orient already sit in Consumer Appliances"),
"BSE:MEHAI":("W","TRADING & DISTRIBUTION","M","Trades electronic items"),
"BSE:RAJESH":("W","POWER T&D EPC","M","EPC/consultancy for transmission and distribution utilities"),
"BSE:SUSAN":("W","WIRES CABLES & CONDUCTORS","H","Winding wires, conductors, power cables"),
"NSE:WSI":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Now operates mainly in infrastructure; insulator business discontinued"),
"BSE:ASMS":("W","IT SERVICES & CONSULTING","M","Ex-Bartronics: barcode/RFID identification solutions"),
"NSE:BIMETAL":("W","BEARINGS","H","Engine bearings, bushings, thrust washers"),
"BSE:REMAGNET":("R",None,"M","Official record: granite/marble; symbol suggests a magnet pivot - confirm"),
"BSE:OLPCL":("W","PRINTING SERVICES","H","Wedding and greeting cards"),
"NSE:SBCL":("K",None,"H","Bimetal strips, shunt resistors"),
"NSE:CNL":("W","IT HARDWARE & DISTRIBUTION","H","Distributor of branded IT/imaging products"),
"BSE:DIGILOGIC":("W","DEFENCE ELECTRONICS","H","Automated test equipment and radars for defence"),
"BSE:NOVATEOR":("W","PERSONAL CARE & HOUSEHOLD PRODUCTS","H","Oral care and personal care products"),
"NSE:VOEPL":("K",None,"M","White goods and EMS"),
"NSE:AXISCADES":("K",None,"M","Engineering services"),
"NSE:TAALTECH":("K",None,"M","Engineering design services (official record describes the pre-demerger charter business)"),
"BSE:JOJO":("W","FILM MUSIC & CONTENT","M","Digital entertainment services"),
"BSE:ROSEMER":("R",None,"M","Vague 'ventures across domains'"),
"BSE:TRESCON":("W","REAL ESTATE DEVELOPMENT","M","Real estate (not the events company of the same name)"),
"BSE:REETECH":("W","COAL & COKE","H","Trades and supplies coal"),
"NSE:AVROIND":("W","FURNITURE & HOME PRODUCTS","H","Plastic furniture and plastic recycling"),
"NSE:EMMBI":("W","PACKAGING PRODUCTS","M","Woven polymer products (FIBC, sacks, agri-polymer)"),
"BSE:GINISILK":("K",None,"H","Fabrics"),
"BSE:GRATEXI":("W","PAPER & PAPERBOARD","H","Paper products"),
"BSE:KUWERIN":("W","FLEXIBLE PACKAGING & FILMS","H","Metallised/embossed polyester and BOPP films"),
"BSE:MIHIKA":("K",None,"M","Fabric trading"),
"BSE:RCL":("K",None,"M","Fabric trading"),
"BSE:SHVSUIT":("K",None,"M","Printed fabrics"),
"BSE:TEXELIN":("W","TECHNICAL TEXTILES","M","Tarpaulins and geomembranes"),
"BSE:ACEMEN":("R",None,"M","Holding company; operating subsidiary is an OEM of indoor/outdoor products - no ferro-alloy business"),
"NSE:RPEL":("W","REFRACTORIES","H","Ramming mass for induction furnaces"),
"BSE:SHAQUAK":("K",None,"M","Film production"),
"NSE:CINEVISTA":("K",None,"M","Media production"),
"NSE:DGCONTENT":("K",None,"M","Entertainment/digital"),
"BSE:IDREAM":("K",None,"M","Film/media"),
"BSE:NOUVEAU":("K",None,"M","Film rights trading plus other"),
"BSE:RACONTEUR":("W","INDUSTRIAL MINERALS & MINING","M","Minerals and stone-mining by-products"),
"BSE:RAP":("W","REAL ESTATE DEVELOPMENT","M","Real estate development and leasing"),
"BSE:REGAL":("W","DIVERSIFIED & OTHER LENDING","H","Agri supply-chain financing NBFC"),
"BSE:SMEL":("K",None,"M","Entertainment"),
"NSE:TPHQ":("R",None,"M","Trading, securities dealing and film content - mixed"),
"BSE:THINKINK":("K",None,"M","TV/film content"),
"NSE:UNIVPHOTO":("W","MEDICAL DEVICES & SUPPLIES","H","X-ray films (medical imaging consumables)"),
"BSE:ZINEMA":("K",None,"M","Film production"),
"BSE:NCLRESE":("W","DIVERSIFIED & OTHER LENDING","M","Finance and investments"),
"BSE:TTGIL":("K",None,"M","Market research and online media"),
"BSE:BGIL":("W","FILM MUSIC & CONTENT","H","Film/content production house ('Films' is cinema, not plastic film)"),
"BSE:PURITY":("K",None,"H","Flexible packaging"),
"BSE:VENLONENT":("R",None,"M","Former polyester-film maker; now only 'purchasing and selling goods'"),
"NSE:TCC":("K",None,"M","Property leasing/management"),
"NSE:GFLLIMITED":("W","INVESTMENT HOLDING COMPANIES","H","Holds investments in associates (post-demerger); no fluorochemical operations"),
"BSE:HINDHARD":("W","AUTO COMPONENTS","H","Propeller shafts"),
"NSE:CRAVATEX":("R",None,"M","Branded sports goods and fitness equipment distribution - not footwear manufacturing"),
"BSE:EUROLED":("W","LEATHER & LEATHER PRODUCTS","H","Leather garments and accessories"),
"NSE:AZAD":("K",None,"M","Precision turbine/aerospace components; kept with your aerospace-precision forgings group"),
"BSE:PRIMAIN":("W","EDIBLE OILS","H","Solvent extraction, edible oil refining, cattle feed"),
"NSE:BALMLAWRIE":("K",None,"M","Diversified PSU incl. logistics"),
"NSE:CMSINFO":("K",None,"M","Cash logistics"),
"BSE:JUJHARLOGI":("K",None,"H","Automotive logistics"),
"NSE:LEAPIND":("K",None,"M","Pallet pooling/supply chain"),
"BSE:PRIMEFRESH":("W","AGRICULTURE & COMMODITY TRADING","M","Procures and sells fruits and vegetables"),
"BSE:PULSRIN":("R",None,"M","Agri supply-chain management - vague"),
"NSE:RADIANTCMS":("K",None,"M","Cash logistics"),
"BSE:REPONO":("K",None,"M","Oil/petchem warehousing and logistics"),
"NSE:SHIPROCKET":("K",None,"M","Shipping/fulfilment platform"),
"NSE:TREJHARA":("W","SOFTWARE PRODUCTS & PLATFORMS","M","Software services and product licensing"),
"BSE:YAANENT":("R",None,"M","Tour operator, gemstones, works contracts"),
"BSE:YURANUS":("W","AGRICULTURE & COMMODITY TRADING","M","Cotton bales and cotton-seed trading"),
"NSE:BELLACASA":("K",None,"M","Home furnishings and ethnic wear"),
"BSE:KUSHIND":("R",None,"M","Official record says only 'trading'"),
"BSE:NATPLAS":("K",None,"H","Plastic furniture"),
"BSE:NATPLASTI":("K",None,"H","Plastic household products"),
"NSE:PRAXIS":("W","RETAIL CHAINS","M","Home retail through department stores (HomeTown)"),
"BSE:SHANGAR":("K",None,"M","Decor services"),
"BSE:YUG":("K",None,"M","Adhesives and plywood"),
"NSE:CFEL":("K",None,"H","CNG/oxygen cylinders"),
"BSE:GUJCONT":("K",None,"H","Steel barrels"),
"BSE:JSLINDL":("W","ELECTRICAL EQUIPMENT","M","Engineering goods (electrical equipment)"),
"BSE:KABSON":("W","PETROLEUM PRODUCTS & TRADING","M","LPG bottling and sales, not cylinder manufacturing"),
"BSE:SARTHAKIND":("K",None,"H","LPG cylinders"),
"BSE:AFEL":("W","TRADING & DISTRIBUTION","M","Plastic products plus trading in fabrics/stones"),
"BSE:HILIKS":("W","IT SERVICES & CONSULTING","M","IT, software and communication solutions"),
"BSE:TRINITYLEA":("W","PROFESSIONAL & BUSINESS SERVICES","M","Financial advisory and management consultancy"),
"NSE:BANARBEADS":("K",None,"M","Glass beads"),
"BSE:UNISON":("R",None,"M","Steel patta, ceramics, sodium silicate - mixed"),
"NSE:KAYA":("W","PERSONAL & HOME SERVICES","M","Skin and hair care clinics"),
"BSE:RELIABVEN":("W","HOTELS & RESORTS","H","Hospitality"),
"NSE:HAVISHA":("W","HOTELS & RESORTS","H","Owns and operates a hotel"),
"BSE:AJWAFUN":("W","LEISURE & GAMING","H","Amusement park"),
"BSE:PGCRL":("K",None,"H","Hotels and clubs"),
"BSE:PECOS":("W","RESTAURANTS & QSR","H","Restaurants and pubs"),
"BSE:WESTLEIRES":("R",None,"M","'Financial and service activities' - no resort operations described"),
"NSE:CORALFINAC":("W","REAL ESTATE DEVELOPMENT","M","Property construction and development; not a housing financier"),
"BSE:AGVENTURES":("W","INVESTMENT HOLDING COMPANIES","M","Investments and trading"),
"BSE:UVDRHOR":("K",None,"M","Precision reconditioning of hydraulic/marine components"),
"BSE:ROBU":("W","E-COMMERCE & INTERNET RETAIL","H","Robu.in e-commerce platform for electronic parts"),
"BSE:UNIOFFICE":("W","IT HARDWARE & DISTRIBUTION","M","Sells and services office automation products"),
"BSE:SCANPRO":("R",None,"M","Engineering services - no engines"),
"BSE:FILTRA":("W","WATER INFRASTRUCTURE & TREATMENT","M","Water treatment systems"),
"BSE:RAJSEC":("W","INVESTMENT HOLDING COMPANIES","H","Ex-Rajasthan Gases; now an investment/securities vehicle"),
"NSE:PIXTRANS":("K",None,"H","Power-transmission belts"),
"BSE:SHREEREF":("K",None,"H","Refrigeration/HVAC systems"),
"NSE:BHARATGEAR":("W","AUTO COMPONENTS","M","Automotive gears"),
"BSE:CHANDNIMACH":("K",None,"M","Engineering goods trading"),
"BSE:DEVSON":("W","SPECIALTY CHEMICALS","M","Catalysts, adsorbents, ceramic balls"),
"BSE:GTTDATA":("W","IT SERVICES & CONSULTING","H","IT consulting and digital transformation"),
"BSE:GOBLIN":("W","LUGGAGE & TRAVEL ACCESSORIES","H","Luggage bags and travel accessories"),
}
