D = {
"BSE:HARDCAS":("R",None,"M","Industrial chemicals, investments and leasing - not machinery"),
"BSE:MILLWORKS":("W","AEROSPACE & DEFENCE MANUFACTURING","M","High-precision aerospace/defence components"),
"BSE:RATHIST":("W","STEEL & IRON","H","Steel products"),
"BSE:REXSEAL":("K",None,"M","Sealing, packing and insulation products"),
"BSE:SYSTEMATIC":("W","STEEL WIRE & WIRE ROPES","H","Steel wires and cables"),
"BSE:TRISHAKT":("W","CONSTRUCTION & MINING EQUIPMENT","M","Heavy earth-moving equipment solutions"),
"NSE:CMPDI":("W","ENGINEERING CONSULTANCY","M","Mine planning, exploration and design consultancy (Coal India subsidiary) - does not mine"),
"BSE:COCHINM":("K",None,"M","Synthetic rutile"),
"BSE:DHINDIA":("W","WELDING & CUTTING EQUIPMENT","H","Welding consumables and cored wire"),
"BSE:GARNETINT":("W","INVESTMENT HOLDING COMPANIES","M","Investments and textiles"),
"BSE:INTLCOMBQ":("W","INDUSTRIAL MACHINERY","M","Heavy engineering equipment, geared motors, gearboxes"),
"BSE:NEELKAN":("K",None,"M","Granite slabs and mineral products"),
"NSE:DEEP":("K",None,"M","Masterbatch and polymers"),
"BSE:DIKSHA":("W","RIGID PLASTIC PACKAGING","H","PET bottles, preforms, caps"),
"BSE:EPBIO":("K",None,"M","FRP products"),
"BSE:GOTHIPL":("W","REAL ESTATE DEVELOPMENT","M","Real estate and related services"),
"BSE:INDOSMC":("K",None,"M","SMC/FRP electrical enclosures"),
"BSE:JAUSPOL":("W","RIGID PLASTIC PACKAGING","H","PET jars/bottles and caps"),
"BSE:KARNAWATI":("W","RIGID PLASTIC PACKAGING","H","Plastic water bottles"),
"BSE:MPL":("R",None,"M","Ceased operations in FY24 after asset sale - shell"),
"BSE:POLYCON":("W","RIGID PLASTIC PACKAGING","M","PET items"),
"BSE:PANKAJPO":("W","TRADING & DISTRIBUTION","M","Trades plastic granules"),
"BSE:POLYLINK":("K",None,"M","Polymer compounds and masterbatch"),
"BSE:SHAMFOAM":("W","FURNITURE & HOME PRODUCTS","M","PU foam and mattresses"),
"BSE:TIRTPLS":("W","TRADING & DISTRIBUTION","M","Trades acrylic sheets and glue"),
"BSE:TIRUFOAM":("W","FURNITURE & HOME PRODUCTS","M","PU foam and foam articles"),
"BSE:VINAYAKPOL":("W","RIGID PLASTIC PACKAGING","H","Plastic bottles and jars"),
"BSE:VINYOFL":("K",None,"M","PVC films and sheets"),
"BSE:POLYCHEM":("W","SPECIALTY CHEMICALS","M","Specialty chemicals plus property development; no rubber products"),
"BSE:BILLWIN":("K",None,"H","Protective gear"),
"BSE:MSAFE":("K",None,"H","Height-safety equipment"),
"BSE:SPAR":("K",None,"M","Power tools"),
"BSE:CHDCHEM":("W","CHEMICAL DISTRIBUTION","H","Trades chemicals and dyes"),
"BSE:CONTCHM":("W","IT SERVICES & CONSULTING","H","IT and software services; no chemicals"),
"BSE:KEMP":("R",None,"M","Real estate, investments, luggage retail"),
"BSE:VRL":("W","PHARMA APIS & INTERMEDIATES","M","Antacid manufacturer/exporter"),
"BSE:YASHCHEM":("W","CHEMICAL DISTRIBUTION","H","Trades chemical products"),
"BSE:ADESHWAR":("W","MEDICAL DEVICES & SUPPLIES","H","Sterile surgical dressings and medical disposables"),
"BSE:BINNYMILLS":("R",None,"M","Services and trading; no textile operations"),
"BSE:CANDOUR":("K",None,"M","Textiles and plastics"),
"BSE:GANVERSE":("W","WASTE MANAGEMENT & RECYCLING","M","Waste and scrap handling"),
"BSE:GARWSYN":("W","SYNTHETIC FIBRES & YARNS","M","Nylon bristles/monofilament"),
"BSE:GETALONG":("W","PROFESSIONAL & BUSINESS SERVICES","H","Tax solutions and allied services"),
"BSE:IGCIL":("W","AGRICULTURE & COMMODITY TRADING","H","Pulses trading and processing"),
"BSE:MODWOOL":("K",None,"M","Suiting/furnishing trading"),
"NSE:RUBFILA":("W","SYNTHETIC RUBBER & LATEX","H","Heat-resistant latex rubber thread"),
"BSE:TRIVENIENT":("W","TRADING & DISTRIBUTION","M","General trading, telecom products distribution"),
"BSE:VICTMILL":("W","REAL ESTATE DEVELOPMENT","H","Primarily real estate development"),
"BSE:LADDU":("W","ADVERTISING & MARKETING","M","Shifted in FY25 to digital-marketing/martech services"),
"NSE:ALEMBICLTD":("K",None,"M","Holding/real estate/pharma"),
"BSE:AIHL":("W","TRADING & DISTRIBUTION","M","Trades textiles and animal-feed supplements"),
"NSE:BNAGROCHEM":("W","EDIBLE OILS","H","Edible oil, oilseeds, solvent extraction"),
"NSE:BBTC":("K",None,"H","Wadia group holding plus plantations"),
"BSE:BOMBCYC":("W","AUTO DEALERSHIPS","M","Car sales/servicing (plus restaurants)"),
"NSE:DVL":("K",None,"M","Treasury and trading"),
"BSE:GANHOLD":("K",None,"M","Investments and loans"),
"NSE:GANGESSECU":("K",None,"M","Group investments plus tea"),
"BSE:GEMSI":("W","DIVERSIFIED & OTHER LENDING","M","Financing activities"),
"BSE:HERCULES":("K",None,"H","Bajaj group core investment company"),
"NSE:KIRLOSIND":("K",None,"H","Kirloskar group CIC"),
"BSE:MARBU":("W","REAL ESTATE DEVELOPMENT","M","Real estate development and works contracts"),
"BSE:MONOT":("K",None,"M","Share trading"),
"NSE:RPSGVENT":("K",None,"M","Diversified holding"),
"BSE:RAJABAH":("W","REAL ESTATE DEVELOPMENT","H","Real estate development and construction"),
"BSE:SW1":("K",None,"H","Investment company"),
"NSE:SECMARK":("W","IT SERVICES & CONSULTING","M","Technology/consulting/outsourcing for capital-market firms"),
"NSE:SHBAJRG":("W","STEEL & IRON","M","Structural steel (plus frozen food, essential oils)"),
"NSE:SIL":("K",None,"M","Property plus trading"),
"NSE:SUPREME":("W","REAL ESTATE DEVELOPMENT","H","Develops commercial and residential projects"),
"BSE:TAIIND":("W","TRADING & DISTRIBUTION","M","Trades food, industrial and mineral products"),
"NSE:TEXINFRA":("K",None,"M","Real estate, hydro, holdings"),
"BSE:TRADEWELL":("K",None,"M","Share trading and real estate"),
"NSE:UNIENTER":("K",None,"M","UPL promoter-group holding/trading"),
"NSE:ZUARIIND":("K",None,"M","Group holding with mixed businesses"),
"NSE:SANDUMA":("K",None,"H","Manganese and iron ore mining"),
"NSE:AVANCE":("W","SOFTWARE PRODUCTS & PLATFORMS","M","Software products"),
"NSE:COMPUSOFT":("W","IT SERVICES & CONSULTING","M","Software/e-governance and education"),
"NSE:EMPOWER":("K",None,"M","IT products"),
"BSE:HYPERSOFT":("W","IT SERVICES & CONSULTING","H","Software development and IT services"),
"BSE:INFRONICS":("W","CLOUD COMMUNICATIONS","M","Enterprise SMS services"),
"NSE:NETWEB":("K",None,"H","High-performance computing hardware"),
"BSE:SHYAMACOMP":("R",None,"M","IT-enabled services plus share trading"),
"BSE:SRSOLTD":("K",None,"H","Computer rental"),
"NSE:SONATSOFTW":("W","IT SERVICES & CONSULTING","M","IT services company; its large India software-resale revenue is low-margin - check whether you placed it here deliberately"),
"BSE:VXLINSTR":("K",None,"H","Thin clients/data processing units"),
"BSE:VIRGOGLOB":("K",None,"M","Computer hardware/software"),
"NSE:ALANKIT":("K",None,"M","E-governance services"),
"BSE:ANKIN":("K",None,"M","IT"),
"BSE:CAPRICORN":("K",None,"M","Programming/consultancy"),
}
