D = {
"BSE:CITYONLINE":("W","TELECOM OPERATORS","M","Internet service provider"),
"BSE:ERPSOFT":("K",None,"M","Software support"),
"BSE:EY":("R",None,"M","Corporate gifting plus IT solutions"),
"BSE:IBINFO":("K",None,"M","IT services"),
"NSE:INDGN":("K",None,"H","Life-sciences tech/analytics services"),
"BSE:INDINFO":("W","DIVERSIFIED & OTHER LENDING","M","Loans and share trading; no IT business"),
"BSE:INDOCITY":("W","DIVERSIFIED & OTHER LENDING","M","Loans and investments"),
"BSE:INFORTEC":("W","BPM & OUTSOURCING SERVICES","H","BPO"),
"BSE:ITCONS":("W","STAFFING & FACILITY MANAGEMENT","H","Recruitment and staffing"),
"BSE:VOLKAI":("R",None,"M","Share trading, fabric, lending plus stated AI business"),
"NSE:LCCINFOTEC":("W","EDUCATION & TRAINING","M","IT/software training institute"),
"BSE:MILLENNIUM":("R",None,"M","Official record says only 'trading'"),
"BSE:NETTLINX":("K",None,"M","Data/voice and software"),
"BSE:ONEINDIG":("W","RENEWABLE ENERGY EPC","H","Solar EPC"),
"BSE:RANJEET":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Fire-protection/MEP turnkey contractor"),
"NSE:STLNETWORK":("K",None,"M","Digital infra and IT services (demerged from STL)"),
"BSE:SAGARSYST":("W","DIVERSIFIED & OTHER LENDING","M","NBFC investment, leasing, financing"),
"BSE:SOFTRAKV":("K",None,"M","Professional/technical services"),
"BSE:SPICELOUNG":("W","RESTAURANTS & QSR","M","Restaurant operator"),
"NSE:TVSELECT":("W","IT HARDWARE & DISTRIBUTION","H","POS devices, printers, keyboards"),
"BSE:VCU":("W","SECURITY & SURVEILLANCE EQUIPMENT","M","Sells surveillance products"),
"BSE:VAMA":("K",None,"M","IT services"),
"NSE:WEWIN":("W","BPM & OUTSOURCING SERVICES","M","Customer-experience/citizen-services outsourcing"),
"BSE:AAYUSHBULL":("K",None,"H","Jewellery"),
"BSE:DEVINE":("K",None,"M","Gems and jewellery"),
"BSE:EFORU":("W","EVENTS & EXHIBITIONS","M","Event management"),
"BSE:GROVY":("W","REAL ESTATE DEVELOPMENT","M","Real estate development and market trading"),
"BSE:OPCHAINS":("K",None,"H","Silver bullion/jewellery trader"),
"BSE:PALMJEWELS":("K",None,"H","Gold jewellery"),
"NSE:SGL":("W","FABRICS & TEXTILE PROCESSING","M","Textile manufacturing"),
"BSE:SITAENT":("W","INVESTMENT HOLDING COMPANIES","M","Investments and finance"),
"BSE:STARLENT":("K",None,"M","Precious metals and jewellery trading"),
"BSE:SVARTCORP":("K",None,"M","Gemstone artefacts"),
"NSE:TAMBOLIIN":("W","INVESTMENT HOLDING COMPANIES","M","Investment/holding company (of Tamboli Castings)"),
"NSE:VEDAVAAG":("W","IT SERVICES & CONSULTING","H","IT sales/services, e-governance"),
"BSE:VEGA":("K",None,"H","Jewellery retail"),
"BSE:BAPACK":("W","PACKAGING PRODUCTS","M","Paper sacks and flexi-packs"),
"BSE:KKALPANAIND":("W","INDUSTRIAL PLASTICS & COMPOSITES","M","Plastic (PVC) compounds/granules"),
"BSE:ROYALCU":("R",None,"M","PVC/vinyl products (flooring, leathercloth) - not leather"),
"BSE:EMERALL":("W","HOTELS & RESORTS","M","Hotel with restaurant/bar"),
"BSE:OMEGAIN":("W","IT SERVICES & CONSULTING","M","IT services"),
"BSE:SGFRL":("K",None,"M","Funicular ropeway (tourism BOT)"),
"NSE:TOYAMSL":("K",None,"M","Sports/fitness/entertainment"),
"NSE:YUDIZ":("K",None,"M","Game/IT development"),
"BSE:JAGANLAM":("W","AUTO ELECTRICALS & ELECTRONICS","H","Automotive bulbs and lights"),
"NSE:LUMINO":("W","WIRES CABLES & CONDUCTORS","M","Conductors/cables for the power sector"),
"BSE:SWORDEDGE":("R",None,"M","Buying and selling goods"),
"BSE:AZTEC":("W","INDUSTRIAL MACHINERY","M","Coding/marking printers and inks - not lubricants"),
"BSE:CONTPTR":("K",None,"H","Lubricants and greases"),
"BSE:JAINEX":("W","INDUSTRIAL TOOLS","H","Gear hobs and cutting tools"),
"NSE:UNIMECH":("W","AEROSPACE & DEFENCE MANUFACTURING","M","Precision aerospace tooling and assemblies"),
"BSE:ABCINDQ":("W","FREIGHT FORWARDING & LOGISTICS","H","Freight services plus fuel station"),
"NSE:SIKA":("W","AEROSPACE & DEFENCE MANUFACTURING","H","Aerospace, defence and space systems"),
"BSE:SKYLMILAR":("W","REAL ESTATE DEVELOPMENT","H","Sells flats and commercial units"),
"NSE:BPL":("W","ELECTRONIC COMPONENTS & MATERIALS","M","Printed circuit boards"),
"NSE:CUPID":("K",None,"M","Condoms and IVD kits"),
"BSE:DHPIND":("W","GAS CYLINDERS & CONTAINERS","M","LPG gas regulators"),
"BSE:DENISCHEM":("W","PHARMA FORMULATIONS","M","IV transfusion solutions"),
"BSE:NEXUSSURGL":("K",None,"M","Medical disposables"),
"BSE:RAAJMEDI":("R",None,"M","Plastic bottles/caps plus sanitary napkins/diapers - mixed"),
"NSE:AEQUS":("W","AEROSPACE & DEFENCE MANUFACTURING","H","Precision aerospace components for global OEMs"),
"BSE:BRADYM":("W","MATERIAL HANDLING EQUIPMENT","H","Material-handling equipment (cranes/hoists)"),
"NSE:INTERARCH":("K",None,"H","Pre-engineered steel buildings"),
"NSE:MBEL":("K",None,"H","Pre-engineered buildings"),
"NSE:MTARTECH":("K",None,"M","Precision components (defence/nuclear/clean energy)"),
"BSE:BELDING":("R",None,"M","Ex-Synthiko Foils; now data-centre EPC, BESS, precision manufacturing"),
"BSE:PGFOILQ":("K",None,"M","Aluminium foil"),
"NSE:GRAVITA":("K",None,"H","Lead recycling"),
"NSE:HRYNSHP":("K",None,"H","Ship breaking"),
"BSE:BLOIN":("K",None,"H","Iron and steel trading"),
"BSE:HVL":("K",None,"H","Iron and steel trading"),
"BSE:LEXORAA":("W","JEWELLERY RETAIL & MANUFACTURING","M","Gems, jewellery and bullion"),
"BSE:SACHEMT":("W","CONSUMER APPLIANCES & ELECTRONICS","M","Aluminium/steel kitchenware and utensils (houseware)"),
"BSE:UNITINT":("K",None,"M","Metals dealing"),
"NSE:VGCL":("W","DIVERSIFIED & OTHER LENDING","M","Lending and investing"),
"BSE:NEWTRAC":("W","AGRICULTURE & COMMODITY TRADING","M","Agri commodity trading"),
"BSE:UVS":("K",None,"M","Food and beverage processing"),
"BSE:BMAL":("W","ALUMINIUM","M","Aluminium sections and ingots"),
"NSE:HISARMETAL":("W","STAINLESS STEEL","H","Stainless steel strips, tubes, pipes"),
"BSE:JTLDEFENCE":("W","COPPER","M","Official record: rolled copper and copper alloys (ex-RCI Industries); check if defence activity has started"),
"BSE:PADALPO":("W","INDUSTRIAL PLASTICS & COMPOSITES","H","Thermoplastic compounds and masterbatches"),
"BSE:SHREMETAL":("W","METAL TRADING","M","Trades ferrous and non-ferrous metals"),
"BSE:DECCAN":("K",None,"M","Consumer health products"),
"BSE:GIANLIFE":("W","DIAGNOSTICS","H","Pathology laboratories"),
"BSE:HANMAN":("W","PERSONAL & HOME SERVICES","M","Runs gyms"),
"NSE:NURECA":("K",None,"M","Home healthcare products"),
"BSE:PHYTO":("W","AGROCHEMICALS","M","Pesticide formulations (plus real estate)"),
"BSE:TSPIRITUAL":("R",None,"M","Official record says only 'trading'"),
"BSE:TAVEXIA":("R",None,"M","Renamed from Sattva Sukun Lifecare; official record describes burners"),
"NSE:TTKHLTCARE":("K",None,"M","Consumer/OTC health brands"),
"NSE:RVTH":("K",None,"H","Drilling rigs"),
"NSE:SOUTHWEST":("K",None,"H","Exploration drilling"),
"BSE:STARLOG":("W","CONSTRUCTION & MINING EQUIPMENT","M","Crane rental"),
"NSE:UNIDT":("K",None,"H","Oil drilling tools"),
"BSE:ANSINDUS":("K",None,"M","Frozen foods"),
"BSE:ALNATRD":("W","AGRICULTURE & COMMODITY TRADING","M","Agro-commodity and coffee trading"),
"BSE:AMBOAGRI":("R",None,"M","Official record: 'manufacturing and trading'"),
"BSE:APOLLOIN":("R",None,"M","Official record says healthcare solutions - conflicts with name"),
"BSE:BPAGRI":("R",None,"M","Renamed from Blue Pearl Texspin; official record still textiles"),
"BSE:CJGEL":("W","GELATIN & FOOD INGREDIENTS","H","Gelatine manufacturer"),
"BSE:CONTILI":("K",None,"M","Food/grocery merchant exporter"),
}
