D = {
"BSE:SUPHA":("W","CHEMICAL DISTRIBUTION","M","Trades APIs, intermediates and pharma chemicals"),
"NSE:DYNPRO":("W","DYES & PIGMENTS","H","Dyes and dye intermediates"),
"BSE:GLEN":("W","PACKAGING PRODUCTS","H","Eco-friendly food packaging and serviceware"),
"BSE:GOEL":("K",None,"M","Sweets/snacks retail plus banquet"),
"BSE:HEALTHYLIFE":("W","MEAT & POULTRY PROCESSING","M","Trades milk, live poultry and fresh meat"),
"BSE:INTEGFD":("W","AGRICULTURE & COMMODITY TRADING","M","Trades oilseeds and agri commodities"),
"BSE:INDGELA":("W","GELATIN & FOOD INGREDIENTS","H","Ossein, DCP and gelatine"),
"NSE:KRITINUT":("W","EDIBLE OILS","H","Soya extraction and cooking oil"),
"NSE:KWIL":("K",None,"H","Ice cream (grouped with Vadilal)"),
"NSE:MEDICAPQ":("R",None,"M","Real estate and pharma"),
"BSE:SHAWGELTIN":("W","GELATIN & FOOD INGREDIENTS","H","Gelatine and ossein"),
"NSE:NATCAPSUQ":("W","PHARMA EXCIPIENTS","M","Empty capsule shells (plus steroidal APIs)"),
"BSE:RIDDHI":("R",None,"M","Windmill power plus commodity trading"),
"BSE:STCORP":("W","REAL ESTATE DEVELOPMENT","H","Real estate development"),
"BSE:SVJ":("K",None,"M","FMCG and packaged food"),
"BSE:SKM":("W","SPECIALTY CHEMICALS","M","Industrial minerals and specialty chemical additives"),
"NSE:SCPL":("K",None,"H","Ice cream, dairy, snacks"),
"BSE:SHREEGANES":("W","AGRICULTURE & COMMODITY TRADING","M","Trades seeds and husk"),
"NSE:TTL":("W","INTEGRATED TEXTILES","M","Yarn trading, fabric and garment manufacturing"),
"NSE:TATACONSUM":("K",None,"H","Foods and beverages"),
"BSE:TEJASSVI":("K",None,"H","Pasta"),
"BSE:TRANSFD":("K",None,"M","Food products"),
"NSE:VADILENT":("K",None,"H","Ice cream distribution"),
"NSE:VADILALIND":("K",None,"H","Ice cream"),
"BSE:ASIAPAK":("W","REAL ESTATE DEVELOPMENT","M","Real estate business"),
"NSE:BI":("K",None,"M","Pharma packaging"),
"NSE:FLEXITUFF":("K",None,"M","FIBC/technical textiles"),
"BSE:KACL":("W","PRINTING SERVICES","M","Printing business"),
"NSE:MOLDTECH":("W","ENGINEERING CONSULTANCY","H","Civil/structural engineering design services - not Mold-Tek Packaging"),
"BSE:SKYIND":("W","TECHNICAL TEXTILES","M","Narrow woven fabrics (hook-and-loop)"),
"BSE:SDL":("R",None,"M","Holding company with various subsidiaries"),
"NSE:SUNLOC":("W","PHARMA EXCIPIENTS","M","Empty hard-gelatin and HPMC capsule shells"),
"BSE:COSYN":("W","IT SERVICES & CONSULTING","H","IT business"),
"BSE:CLARA":("W","FLEXIBLE PACKAGING & FILMS","H","Flexible packaging"),
"NSE:HINDADH":("K",None,"H","Adhesive tapes"),
"BSE:METALCO":("W","STEEL & IRON","H","Cold-rolled steel strips"),
"BSE:SHGANEL":("W","AGRICULTURE & COMMODITY TRADING","M","Agri trading and securities"),
"BSE:GEL":("K",None,"M","Waste-paper trading"),
"NSE:SIEL":("W","PACKAGING PRODUCTS","H","Corrugated boxes"),
"NSE:VOITHPAPR":("W","TECHNICAL TEXTILES","M","Paper-machine clothing (supplier to paper mills, not a paper maker)"),
"BSE:WIREFABR":("W","TECHNICAL TEXTILES","M","Forming fabrics for paper machines"),
"NSE:ALGOQUANT":("W","STOCKBROKING & INVESTMENT BANKING","M","Proprietary/algo trading in financial instruments"),
"BSE:EBIX":("K",None,"M","Eraaya Lifespaces - owner of Ebix (fintech/insurance software)"),
"NSE:ISFT":("W","E-COMMERCE & INTERNET RETAIL","H","US e-commerce retail platform"),
"BSE:JMJFIN":("W","DIVERSIFIED & OTHER LENDING","M","Loans and investments"),
"BSE:NIYOGIN":("K",None,"H","Fintech NBFC"),
"NSE:APTECHT":("W","EDUCATION & TRAINING","H","Education and training centres"),
"BSE:KDML":("W","TRADING & DISTRIBUTION","M","Distributor of HUL products"),
"NSE:MKEXIM":("W","FABRICS & TEXTILE PROCESSING","M","Finished fabrics and garments (cosmetics is minor)"),
"NSE:MARICO":("K",None,"H","FMCG"),
}
