D = {
"BSE:NEERAJ":("K",None,"M","Paper trading/marketing"),
"BSE:LYKISLTD":("W","TRADING & DISTRIBUTION","M","Exports/distributes FMCG and cosmetic products (renamed Krowniq)"),
"BSE:PAOS":("K",None,"M","Soap and detergent"),
"BSE:RONI":("W","TRADING & DISTRIBUTION","M","Trades plastic granules and household products"),
"BSE:JASCH":("W","TECHNICAL TEXTILES","M","Coated textiles and synthetic leather"),
"BSE:KGPETRO":("W","INTEGRATED TEXTILES","M","Mainly textiles and garments (plus polymer distribution)"),
"BSE:RAJSPTR":("R",None,"M","Office management / C&F agency - shell"),
"BSE:SHISHIND":("W","INDUSTRIAL PLASTICS & COMPOSITES","H","PP sheets and rolls"),
"BSE:SHUBHAM":("W","SYNTHETIC FIBRES & YARNS","H","Multifilament yarn"),
"BSE:ZENIFIB":("W","SYNTHETIC FIBRES & YARNS","H","Polypropylene staple fibre and yarn"),
"BSE:ASINPET":("K",None,"M","Petro products"),
"NSE:GOACARBON":("W","GRAPHITE & CARBON MATERIALS","M","Calcined petroleum coke - same bucket as Rain Industries"),
"BSE:SAMYAKINT":("K",None,"M","Petrochemical trading"),
"BSE:SURJIND":("W","ALCOHOLIC BEVERAGES","H","Bottles and packs alcoholic beverages"),
"BSE:PNTKYOR":("W","PHARMA DISTRIBUTION & RETAIL","M","Trades pharmaceutical products"),
"BSE:SAFFRON":("W","PAPER & PAPERBOARD","M","Paper manufacturing (plus real estate)"),
"NSE:SHIVALIK":("R",None,"M","Agrochemical technicals and pharma APIs - check revenue split"),
"BSE:SHREYASI":("W","DYES & PIGMENTS","H","Phthalocyanine blue crude (pigment)"),
"BSE:VIKRAMTH":("W","PHARMA EXCIPIENTS","M","Pharma co-polymers"),
"BSE:ACHYUT":("K",None,"M","Pharma/API trading"),
"BSE:MAITRI":("K",None,"M","Pharma goods trading"),
"NSE:ORTINGLOBE":("W","PHARMA FORMULATIONS","M","Formulations manufacturer"),
"BSE:PRISMMEDI":("K",None,"M","Pharma trading/distribution"),
"BSE:AMERISE":("K",None,"M","Complex formulations"),
"BSE:DEVLAB":("W","JEWELLERY RETAIL & MANUFACTURING","H","Polished and lab-grown diamonds"),
"BSE:EIKO":("W","SPECIALTY CHEMICALS","H","Specialty and fine chemicals"),
"BSE:EVOQ":("K",None,"M","Pharma"),
"BSE:GENPHARMA":("K",None,"M","Pharma services plus share trading"),
"BSE:JOHNPHARMA":("W","INVESTMENT HOLDING COMPANIES","M","Investment-focused; no demonstrated pharma operations"),
"BSE:MAHALIFE":("W","AGROCHEMICALS","H","Crop-protection and bio-products"),
"BSE:NORRIS":("K",None,"H","Injections and formulations"),
"BSE:PANJON":("K",None,"M","Consumer and pharma products"),
"BSE:VANTABIO":("W","PHARMA CONTRACT RESEARCH & MANUFACTURING","H","Pre-clinical contract research organisation"),
"BSE:ZENLABS":("K",None,"M","Pharma marketing"),
"BSE:ISERA":("R",None,"M","Renamed from Covidh Technologies; official record still IT/ITES"),
"BSE:AMBIT":("R",None,"M","Now construction job-work; no plastics machinery"),
"NSE:CONTROLPR":("K",None,"H","Coding and marking machines"),
"BSE:AREXMIS":("W","FABRICS & TEXTILE PROCESSING","M","Woven and printed labels, not pipes"),
"NSE:DDEVPLSTIK":("W","INDUSTRIAL PLASTICS & COMPOSITES","M","Plastic compounds (cable compounds), not pipes"),
"NSE:MAHEPC":("K",None,"H","Micro-irrigation"),
"NSE:AKI":("W","LEATHER & LEATHER PRODUCTS","H","Leather products"),
"BSE:ALFAICA":("K",None,"H","Laminates"),
"BSE:DECOMIC":("K",None,"H","Laminates"),
"BSE:MEGAMONT":("K",None,"M","Wood products"),
"BSE:SCTL":("K",None,"M","Laminate/plywood trading"),
"NSE:AEGISLOG":("K",None,"H","Liquid/gas terminals"),
"NSE:RUCHINFRA":("K",None,"M","Storage infrastructure"),
"BSE:ELANGO":("R",None,"M","O&M services"),
"BSE:KEIL":("W","STONE & OTHER BUILDING MATERIALS","H","Asbestos-cement pipes and sheets - peers Visaka/Everest/Ramco sit there"),
"NSE:PRABHA":("W","OIL & GAS EXPLORATION","H","Oil and gas E&P"),
}
