D = {
"NSE:AEGISVOPAK":("K",None,"H","LPG/liquid storage terminals"),
"BSE:KTIL":("K",None,"H","Liquid storage tanks"),
"BSE:RAGHUSYN":("W","HOME TEXTILES","H","Fabrics and home-textile made-ups; no power electronics"),
"NSE:GUJENERGY":("W","CITY GAS DISTRIBUTION","M","Official classification and profile are Gujarat Gas's city-gas business (LPG/CNG/PNG supplier), not power generation"),
"BSE:SULABEN":("W","DIVERSIFIED & OTHER LENDING","M","Lending and agricultural activities"),
"NSE:RMC":("W","POWER T&D EPC","M","Switchgear engineering and power-distribution EPC; not a utility"),
"BSE:NAKSH":("W","JEWELLERY RETAIL & MANUFACTURING","M","Jewellery manufacturing and distribution"),
"BSE:PANTH":("R",None,"M","Digital business services"),
"NSE:DICIND":("W","PAINTS COATINGS & ADHESIVES","M","Printing inks and lamination adhesives (a chemical maker, not a printer)"),
"BSE:GGPL":("W","STATIONERY & EDUCATION PRODUCTS","H","Stationery and educational toys"),
"BSE:LABELKRAFT":("W","IT HARDWARE & DISTRIBUTION","M","Barcode scanners and RFID printers"),
"NSE:ORIENTLTD":("K",None,"M","Printing and packaging"),
"NSE:STYL":("K",None,"M","Card/payment printing and fulfilment"),
"NSE:SHILGRAVQ":("K",None,"M","Engraved printing rollers"),
"BSE:STOVACQ":("W","TEXTILE MACHINERY","M","Textile machinery and consumables (rotary screens)"),
"NSE:GOLDTECH":("W","IT SERVICES & CONSULTING","M","IT/ITES"),
"NSE:BLS":("K",None,"H","Visa outsourcing"),
"BSE:CENTUPLE":("R",None,"M","Trading and consultancy"),
"BSE:ESHAMEDIA":("K",None,"M","Media monitoring"),
"BSE:FORINTL":("W","INVESTMENT HOLDING COMPANIES","M","Non-operating parent holding a granite-mining associate"),
"BSE:ISLCONSUL":("W","INVESTMENT HOLDING COMPANIES","M","Securities trading"),
"BSE:INNOKAIZ":("K",None,"M","Corporate services"),
"BSE:KWICK":("K",None,"M","Forensic services"),
"BSE:MPILCORPL":("K",None,"M","Support services and leasing"),
"BSE:NMSGLOBAL":("R",None,"M","Trading and consultancy"),
"BSE:RICHUNV":("W","DIVERSIFIED & OTHER LENDING","M","Financial services"),
"NSE:SEMAC":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Renamed to Semac Construction; engineering/construction of industrial projects"),
"BSE:SUMERUIND":("K",None,"M","Management services"),
"BSE:VIVANTA":("R",None,"M","Turnkey projects, tech supply, trading - mixed"),
"BSE:JUPITERIN":("R",None,"M","Now Arix Energix after change of control; legacy web portals plus treasury"),
"BSE:SPENTA":("W","APPAREL MANUFACTURING","H","Socks manufacturer/exporter"),
"NSE:GKENERGY":("K",None,"M","Solar pump EPC (PM-KUSUM)"),
"NSE:JITFINFRA":("W","WATER INFRASTRUCTURE & TREATMENT","M","Water/urban infrastructure and waste-to-energy"),
"BSE:KRRAIL":("W","RAILWAY EPC","H","Builds private railway sidings on turnkey basis"),
"NSE:KERNEX":("K",None,"H","Railway safety systems"),
"NSE:QUADFUTURE":("K",None,"H","Train control and specialty cables"),
"NSE:3PLAND":("K",None,"M","CIC plus property leasing"),
"NSE:ALFREDHE":("W","INVESTMENT HOLDING COMPANIES","M","NBFC and investment/realty holding company"),
"BSE:ARIGATO":("R",None,"M","IT services plus construction materials trading"),
"NSE:ASHIMASYN":("K",None,"M","Textiles, real estate, treasury"),
"NSE:BLAL":("K",None,"H","BEML surplus land"),
"BSE:BSELALGO":("R",None,"M","Algorithmic trading plus real estate"),
"BSE:BHARATAGRI":("K",None,"M","Real estate plus fertilisers"),
"NSE:BOMDYEING":("K",None,"M","Real estate, PSF, textiles retail"),
"NSE:BRAHMINFRA":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","EPC for bridges, flyovers, highways"),
"BSE:CITYMAN":("K",None,"M","Garments plus real estate"),
"BSE:DHENUBUILD":("W","INVESTMENT HOLDING COMPANIES","M","Investment services"),
"BSE:DML":("K",None,"M","Real estate"),
"BSE:DRL":("W","INVESTMENT HOLDING COMPANIES","M","Securities trading"),
"BSE:EMROCK":("K",None,"M","TDR and real estate"),
"NSE:FMNL":("K",None,"M","Leases commercial units"),
"BSE:GGDPROP":("K",None,"H","Commercial real estate leasing"),
"NSE:GARUDA":("W","CONSTRUCTION & INFRASTRUCTURE EPC","H","Civil construction contractor"),
"BSE:GENUSPRIME":("K",None,"M","Infra and real estate"),
"NSE:HEMIPROP":("K",None,"H","Surplus land holding"),
"BSE:KCDGROUP":("K",None,"M","Construction"),
"BSE:KALIND":("W","CONSTRUCTION & MINING EQUIPMENT","M","Heavy machinery rental with operators"),
"BSE:LAKESHORE":("K",None,"M","Real estate"),
"NSE:LANDSMILL":("K",None,"M","Infra development plus services"),
"BSE:LASTMILE":("K",None,"M","Real estate"),
"BSE:KARANWO":("K",None,"M","Real estate"),
"BSE:MAINFRA":("K",None,"M","Real estate"),
"NSE:METROGLOBL":("W","TRADING & DISTRIBUTION","M","Trades chemicals, textiles, minerals, metals (plus some realty)"),
"NSE:NAVKARURB":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Infrastructure construction and RCC pipes"),
"BSE:NEWINFRA":("K",None,"M","Real estate"),
"NSE:NIRLON":("K",None,"H","IT park owner"),
"BSE:NYSSACORP":("K",None,"M","Real estate"),
"NSE:ORIENTALTL":("W","STONE & OTHER BUILDING MATERIALS","H","Imported marble supplier"),
"BSE:PARLEIND":("K",None,"M","Infra and real estate"),
"BSE:PARSHVA":("W","JEWELLERY RETAIL & MANUFACTURING","M","Buys and sells diamonds"),
"BSE:POPULARES":("K",None,"M","Construction and development"),
"NSE:RRIL":("K",None,"M","Textiles and real estate"),
"NSE:RAYMOND":("W","AUTO COMPONENTS","M","Raymond Realty is now separately listed (already in your Real Estate bucket); Raymond Ltd is now an engineering business (auto components, aerospace)"),
"BSE:RISAINTL":("K",None,"M","Trading and realty"),
"NSE:RUBYMILLS":("K",None,"M","Textiles and real estate"),
"BSE:SANINFRA":("W","PETROLEUM PRODUCTS & TRADING","M","Petroleum products (bitumen) trading"),
"NSE:SCILAL":("K",None,"H","SCI non-core land"),
"BSE:SHREESHAY":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Construction contractor"),
"BSE:SFPIL":("K",None,"M","Infra and real estate"),
"BSE:STRGRENWO":("K",None,"M","Real estate and resorts"),
"BSE:TCMLMTD":("R",None,"M","Solar panels, healthcare products, cattle feed"),
"BSE:THRIVE":("K",None,"M","Real estate"),
"BSE:ESPIRE":("W","HOTELS & RESORTS","H","Hotel operations"),
"BSE:INDIAHOMES":("R",None,"M","Renamed from India Steel Works; official record still steel - confirm real-estate pivot"),
"BSE:AHASOLAR":("K",None,"M","Renewable-energy digital advisory"),
"BSE:BONDADA":("K",None,"M","Telecom and solar EPC"),
"BSE:JETSOLAR":("K",None,"M","Solar"),
"BSE:SBL":("K",None,"M","Solar trading/EPC"),
"BSE:SHRICON":("W","CONSTRUCTION & INFRASTRUCTURE EPC","M","Civil works"),
"BSE:EPIC":("K",None,"H","Rooftop solar/EPC"),
"BSE:REALECO":("W","METAL TRADING","M","Trades TMT bars"),
"BSE:TIMESGREEN":("R",None,"M","Agriculture and hygiene products"),
"BSE:INDSILHYD":("W","FERRO ALLOYS","H","Silico-manganese"),
"NSE:RELTD":("K",None,"M","Solar pumps/plants and power sale"),
"NSE:SAMPANN":("R",None,"M","Renewable power plus reclaimed rubber"),
"NSE:SRIKPRIND":("W","STONE & OTHER BUILDING MATERIALS","M","Asbestos-cement pressure pipes"),
"NSE:SWELECTES":("K",None,"H","Solar"),
"BSE:TARINI":("R",None,"M","Power-sector engineering, consultancy and turnkey contracts"),
"BSE:SATCH":("K",None,"M","Holding with catering/restaurants"),
"BSE:CHANDRAP":("W","TRADING & DISTRIBUTION","M","Trades coal, metals, agro products"),
}
