# Renders ../CHECKLIST.md from sections.json + urls.json + frag META titles.
# Run from b1/ after every publish:  python mkchecklist.py
import json, io, os, re, datetime, collections

S = json.load(io.open('sections.json', encoding='utf-8'))
U = json.load(io.open('urls.json', encoding='utf-8'))

def title(no):
    if no == '001':
        return 'Agrochemicals'
    f = f'frag_{no}.html'
    if os.path.exists(f):
        m = re.search(r'<!--META(\{.*?\})-->', io.open(f, encoding='utf-8').read(), re.S)
        if m:
            return json.loads(m.group(1)).get('short', no).replace('&amp;', '&')
    return no

bad = [k for k, v in U.items() if not v.startswith('http')]
if bad:
    raise SystemExit(f'urls.json has bare ids (must be full https URLs): {bad}')

done = [s for s in S if s['status'] == 'done']
queued = sorted([s for s in S if s['status'] == 'queued'], key=lambda s: s['order'])
deferred = sorted([s for s in S if s['status'] == 'deferred'], key=lambda s: s['order'])
primers = sorted(set(s['primer'] for s in done))
missing_url = [p for p in primers if p not in U]

L = []
L.append('# Industry Primer Checklist')
L.append('')
L.append(f'_Generated {datetime.date.today():%d %b %Y} from `b1/sections.json`. Do not edit this file by hand — edit `sections.json` and run `python mkchecklist.py` in `b1/`._')
L.append('')
L.append(f'**{len(primers)} primers published**, covering **{len(done)} of 278** watchlist sections. '
         f'**{len(queued)} sections queued**, **{len(deferred)} deferred to the end** at Prerak\'s instruction.')
if missing_url:
    L.append(f'\n> WARNING: published primers with no URL in urls.json: {missing_url}')
L.append('')
L.append('## How to use this file')
L.append('')
L.append('1. The next primer is the **lowest-numbered queued section** below (after merging any siblings its note suggests).')
L.append('2. Deferred sections are done **only after every queued section is finished** — his standing instruction.')
L.append('3. After publishing, set each covered section to `"status": "done", "primer": "NNN"` in `sections.json`, save the full artifact URL in `urls.json`, and re-run `mkchecklist.py`.')
L.append('4. Primer numbers are assigned in publication order, so the next primer is always one higher than the last number below.')
L.append('')

L.append('## Next up')
L.append('')
L.append('| Order | Section | Names | Family | Note |')
L.append('|---:|---|---:|---|---|')
for s in queued[:12]:
    L.append(f"| {s['order']} | {s['section'].title()} | {s['members']} | {s['family']} | {s['note']} |")
L.append('')

L.append('## Published')
L.append('')
L.append('| # | Primer | Sections covered | Family | Link |')
L.append('|---|---|---|---|---|')
by_p = collections.defaultdict(list)
for s in done:
    by_p[s['primer']].append(s)
for p in primers:
    secs = by_p[p]
    covered = '; '.join('%s (%d)' % (x['section'].title(), x['members']) for x in secs)
    L.append(f"| {p} | {title(p)} | {covered} | {secs[0]['family']} | {U.get(p, 'MISSING')} |")
L.append('')

def fam_table(rows, heading):
    L.append(heading)
    L.append('')
    fams = collections.OrderedDict()
    for s in rows:
        fams.setdefault(s['family'], []).append(s)
    for f, items in fams.items():
        L.append(f"### {f} — {len(items)} sections, {sum(x['members'] for x in items)} names")
        L.append('')
        L.append('| Order | Section | Names | Note |')
        L.append('|---:|---|---:|---|')
        for s in items:
            L.append(f"| {s['order']} | {s['section'].title()} | {s['members']} | {s['note']} |")
        L.append('')

fam_table(queued, '## Queue, by family')
fam_table(deferred, '## Deferred to the end (financials, capital markets, insurance, pharma, healthcare, hospitals, hotels)')

L.append('## Watchlist coverage')
L.append('')
L.append('| Watchlist | Sections | Done | Queued | Deferred |')
L.append('|---|---:|---:|---:|---:|')
W = collections.OrderedDict()
for s in S:
    W.setdefault(s['watchlist'], collections.Counter())[s['status']] += 1
for w, c in W.items():
    L.append(f"| {w} | {sum(c.values())} | {c['done']} | {c['queued']} | {c['deferred']} |")
L.append('')

io.open('../CHECKLIST.md', 'w', encoding='utf-8').write('\n'.join(L))
print(f'CHECKLIST.md written: {len(primers)} primers, {len(done)} done, {len(queued)} queued, {len(deferred)} deferred')
